---
sidebar: sidebar 
permalink: concept_vcp_product_overview.html 
summary: コンポーネントや重要な URL など、プラグインに関する概要情報。 
keywords: netapp, vcp, element, vcenter plugin, plug-in 
---
= NetApp Element Plug-in for vCenter Server の製品概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, vcp, element, vcenter plugin, plug-in


[role="lead"]
NetApp Element Plug-in for vCenter Server （ VCP ）は Web ベースのツールで、 VMware vSphere Web Client ユーザインターフェイス（ UI ）に統合されます。このプラグインは、拡張機能として VMware vSphere に対応した使いやすいインターフェイスで、 * NetApp Element ソフトウェア * を実行しているストレージ・クラスタを管理および監視することができます。

プラグインのユーザインターフェイスを使用して、クラスタの検出と設定、ストレージの管理と監視が可能なほか、クラスタ容量からストレージを割り当ててデータストアや仮想データストア（仮想ボリュームの場合）を構成できます。クラスタはネットワーク上では 1 つのローカルグループとして認識され、仮想 IP アドレスによってホストと管理者に示されます。また、クラスタのアクティビティを監視して、さまざまな処理の実行中に発生したイベントのエラーメッセージやアラートメッセージなど、リアルタイムで通知を受け取ることができます。



== プラグインに関連するネットアップのコンポーネント

* * 登録ユーティリティ * ：を管理するためのツール link:vcp_concept_qossioc.html["QoSSIOC"] vCenter へのサービスおよびプラグインの登録
* * 管理サービス * ： vCenter Plug-in の QoSSIOC サービスを含むマイクロサービス。プラグインのアップグレードは、管理サービスバンドルの一部としてリリースされます。
+

TIP: の詳細を確認してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスのリリース"^]。

* * 管理ノード（ mNode ） * ： Element ソフトウェアベースの 1 つ以上のストレージクラスタと同時に実行される仮想マシン。Element 11.3 リリース以降、管理サービスは管理ノードでホストされるようになりました。そのため、メジャーリリースを待つことなく、希望するソフトウェアサービスを更新できます。




== 共通 URL

vSphere に加え、 vCenter プラグインで使用する一般的な URL の一部を次に示します。

[cols="2*"]
|===
| URL | 説明 


| 「 https://[management node IP address 」 : 9443 | vCenter Plug-in パッケージを vSphere Web Client に登録します。 


| https://[management ノード IP アドレス :442` | 管理ノードのノード UI から、ネットワークとクラスタの設定にアクセスし、システムのテストとユーティリティを利用できます。 https://docs.netapp.com/us-en/hci/docs/task_mnode_access_ui.html["詳細はこちら。"^] 


| https://[management ノード IP アドレス | NetApp Hybrid Cloud Control にアクセスして、管理サービスをアップグレードするか、インストール環境を拡張、監視、管理します。 https://docs.netapp.com/us-en/hci/docs/task_hci_getstarted.html["詳細はこちら。"^] 


| 「 https://[management node IP address 」 /mnode 」を参照してください | 管理ノードから REST API UI を使用して、管理サービスを手動で更新したりアセットを管理したりできます。 https://docs.netapp.com/us-en/hci/docs/task_mnode_access_ui.html["詳細はこちら。"^] 


| https://[storage クラスタ MVIP アドレス ' | NetApp Element ソフトウェア UI にアクセスします。 
|===
[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* http://mysupport.netapp.com/hci/resources["NetApp HCI のリソースページ"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire および Element ソフトウェアのドキュメント"^]
* link:vcp_concept_config_extension_point.html["NetApp Element Configuration 拡張ポイント"]
* link:vcp_concept_management_extension_point.html["NetApp Element Configuration 拡張ポイント"]

