---
sidebar: sidebar 
permalink: rn_whatsnew_vcp.html 
summary: このバージョンのNetApp Element Plug-in for VMware vCenter Serverの新機能について説明します。 
keywords: netapp, vcp, vcenter, plugin, element, new, whats new 
---
= NetApp Element Plug-in for VMware vCenter Serverの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element Plug-in for vCenter Server 5.2では、サポート性が向上し、カスタムの保護ドメイン表示が強化されています。

バージョン5.2では、Elementソフトウェアクラスタにカスタム保護ドメインが設定されている場合、プラグインに[Custom Protection Domain Health]情報が表示されます。 link:vcp_task_reports_overview.html#reporting-overview-page-data["詳細はこちら。"]。

Element vCenter Plug-in 5.2は、管理サービスの2.24.40リリースで使用できます。



== vCenter Server 5.1向けNetApp Elementプラグイン

NetApp Element Plug-in for vCenter Server 5.1を使用すると、セキュリティとパフォーマンスが向上します。 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885734["詳細はこちら。"^]。



== vCenter Server 5.0向けNetApp Element プラグイン

NetApp Element Plug-in for vCenter Server 5.0には、プラグインのリモートアーキテクチャが含まれています。このアーキテクチャは、vCenter Server内でプラグインを実行することなく、vSphere Clientにプラグイン機能を統合するように設計されています。リモートアーキテクチャではプラグインの分離がサポートされており、大規模なvSphere環境で動作するプラグインのスケールアウトが可能です。リモートのElement Plug-inは、管理サービスとともに管理ノード内のDockerコンテナに導入されます。 link:vcp_concept_remote_plugin_architecture.html["詳細はこちら。"]。

Element vCenterプラグイン5.0は、VMware vSphere 8.0、7.0、7.0 Update 1、2、3（vCenter Server、ESXi、vSphere HTML5 Web Clientを含む）をサポートしています。

Element vCenterプラグイン5.0は、管理サービスの2.22.7リリースで使用できます。このプラグインを使用しない場合、他のすべてのサービスと機能はバージョン2.2.61と同じであるため、このアップグレードはオプションです。管理サービスの最新の更新情報については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2884458["管理サービスリリースノート2.1.61"^]。



== vCenter Server 4.10用NetApp Element プラグイン

Element vCenter Plug-in 4.10には、セキュリティの脆弱性など、解決済みの問題が含まれています。アップグレード中に発生する中断を大幅に減らし、一部の環境で日常の運用を強化することができます。本プラグインのバージョン4.10では、オンライン・ヘルプ・リンクがこのファイルに移行しています link:index.html["マニュアルへのリンク"]。プラグイン内からオンラインヘルプのリンクにアクセスするには、ネットワークアクセスが必要です。

Element vCenter Plug-in 4.10は、管理サービスの2.2.61リリースで使用できます。



== NetApp Element Plug-in for vCenter Server 4.9

NetApp Element Plug-in for vCenter Server 4.9は、vCenter Server、ESXi、vSphere HTML5 Web Clientを含むvSphere 6.5をサポートしています。

Element vCenter Plug-in 4.9は、管理サービスの2.20.69リリースで使用できます。



== NetApp Element Plug-in for vCenter Server 4.8の略

Element vCenterプラグイン4.8では、セキュリティの向上、メモリ使用率の向上、およびサードパーティ製ライブラリのアップグレードが実装されています。

Element vCenterプラグイン4.8は、管理サービスの2.19リリースで提供されています。



== NetApp Element Plug-in for vCenter Server 4.7

Element vCenterプラグイン4.7では、さらに改良されたセキュリティ機能が強化されています https://security.netapp.com/advisory/ntap-20210315-0001/["最新の管理サービス 2.17.56 パッチ"] リリース。

バージョン 4.7 では、 vCenter Server 、 ESXi 、 vSphere HTML5 Web Client など、 vSphere 7.0 Update 2 のコンポーネントがサポートされるようになりました。

Element vCenterプラグイン4.7は、2.18リリースの管理サービスで使用できます。



== NetApp Element Plug-in for vCenter Server 4.6

バージョン 4.6 では、 vCenter Server 、 ESXi 、 vSphere HTML5 Web Client など、 vSphere 7.0 Update 1 のコンポーネントがサポートされるようになりました。

Element vCenter Plug-in 4.6は、2.16リリースの管理サービスで使用できます。



== 詳細については、こちらをご覧ください

* link:reference_earlier_versions.html["以前のバージョンの NetApp Element プラグインのドキュメント"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Hybrid Cloud Control and Management Services リリースノート KB"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

