---
sidebar: sidebar 
permalink: rn_whatsnew_vcp.html 
summary: このバージョンの NetApp Element Plug-in for vCenter Server の新機能について説明します。 
keywords: netapp, vcp, vcenter, plugin, element, new, whats new 
---
= NetApp Element Plug-in for vCenter Server の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, vcp, vcenter, plugin, element, new, whats new


[role="lead"]
NetApp Element Plug-in for vCenter Server 4.9は、vCenter Server、ESXi、vSphere HTML5 Web Clientを含むvSphere 6.5をサポートしています。

NetApp Element Plug-in for vCenter Server 4.9は、管理サービスの2.20リリースで使用できます。



== NetApp Element Plug-in for vCenter Server 4.8の略

NetApp Element Plug-in for vCenter Server 4.8 では、セキュリティの向上、メモリ使用率の向上、および他社製ライブラリのアップグレードが実装されています。

NetApp Element Plug-in for vCenter Server 4.8 は、 2.19 リリースの管理サービスで使用できます。



== NetApp Element Plug-in for vCenter Server 4.7

NetApp Element Plug-in for vCenter Server 4.7 では、セキュリティがさらに強化され、でさらに強化された機能が追加されています https://security.netapp.com/advisory/ntap-20210315-0001/["最新の管理サービス 2.17.56 パッチ"] リリース。

バージョン 4.7 では、 vCenter Server 、 ESXi 、 vSphere HTML5 Web Client など、 vSphere 7.0 Update 2 のコンポーネントがサポートされるようになりました。

NetApp Element Plug-in for vCenter Server 4.7 は、 2.18 リリースの管理サービスで使用できます。



== NetApp Element Plug-in for vCenter Server 4.6

バージョン 4.6 では、 vCenter Server 、 ESXi 、 vSphere HTML5 Web Client など、 vSphere 7.0 Update 1 のコンポーネントがサポートされるようになりました。

NetApp Element Plug-in for vCenter Server 4.6 は、 2.16 リリースの管理サービスで使用できます。

[discrete]
== 詳細については、こちらをご覧ください

* link:reference_earlier_versions.html["以前のバージョンの NetApp Element プラグインのドキュメント"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Hybrid Cloud Control and Management Services リリースノート KB"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

