---
sidebar: sidebar 
permalink: vcp_task_protect_remote_replication.html 
summary: リアルタイムレプリケーションを使用すると、ボリュームデータのリモートコピーを迅速に作成できます。 
keywords: netapp, hci, vcp, vcenter, element, protect, replication, remote, cluster 
---
= クラスタ間でリモートレプリケーションを実行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element ソフトウェアを実行するクラスタでは、リアルタイムレプリケーションを使用してボリュームデータのリモートコピーを迅速に作成できます。1 つのストレージクラスタを最大 4 つの他のストレージクラスタとペアリングすることができます。

フェイルオーバーやフェイルバックの際には、クラスタペアのどちらかのクラスタからボリュームのデータを同期または非同期でレプリケートできます。リアルタイムのリモートレプリケーションを利用するには、 2 つの NetApp Element クラスタをペアリングしてから、各クラスタのボリュームをペアリングする必要があります。

.必要なもの
* プラグインにクラスタを少なくとも 1 つ追加しておきます。
* 管理ネットワークとストレージネットワーク両方のすべてのノード IP アドレスを、ペアクラスタ間で相互にルーティングする必要があります。
* すべてのペアノードの MTU が同じであり、クラスタ間でエンドツーエンドでサポートされていることを確認してください。
* クラスタの NetApp Element ソフトウェアのバージョンの違いが 1 メジャーバージョン以内である必要があります。それよりも離れている場合、データレプリケーションを実行するには一方のクラスタをアップグレードする必要があります。



NOTE: データのレプリケーションにおける WAN アクセラレータアプライアンスの使用は、ネットアップで認定されていません。データをレプリケートする 2 つのクラスタ間にこのアプライアンスを配置すると、圧縮および重複排除の妨げとなる場合があります。WAN アクセラレータアプライアンスを本番環境に導入する前に、影響を十分に検証してください。

.手順
.  clusters
.  volumes
.  volume replication
.  a volume relationship after replication
.  volume relationships




== クラスタをペアリング

リアルタイムレプリケーション機能を使用するには、最初に 2 つのクラスタをペアリングする必要があります。2 つのクラスタをペアリングして接続したあと、一方のクラスタのアクティブなボリュームをもう一方のクラスタに継続的にレプリケートするように設定することで継続的なデータ保護（ CDP ）を実現できます。

両方のクラスタにクラスタ管理者としてアクセスできる場合は、ターゲットクラスタの MVIP を使用してソースとターゲットのクラスタをペアリングできます。クラスタペアの一方のクラスタにしかクラスタ管理者としてアクセスできない場合は、ターゲットクラスタでペアリングキーを使用してクラスタをペアリングします。

.必要なもの
* ペアリングするクラスタの一方または両方に対するクラスタ管理者権限が必要です。
* クラスタ間のラウンドトリップレイテンシが 2 、 000 ミリ秒未満である必要があります。
* クラスタの NetApp Element ソフトウェアのバージョンの違いが 1 メジャーバージョン以内である必要があります。
* ペアクラスタのすべてのノード IP を相互にルーティングする必要があります。



NOTE: クラスタをペアリングするには、管理ネットワーク上のノードどうしが完全に接続されている必要がレプリケーションを実行するには、ストレージクラスタネットワーク上の個々のノードが接続されている必要があります。

ボリュームのレプリケーション用に、 1 つの NetApp Element クラスタを最大 4 つの他のクラスタとペアリングすることができます。同じクラスタグループに含まれるクラスタどうしをペアリングすることもできます。

次のいずれかの方法を選択します。

*  clusters using known credentials
*  clusters with a pairing key




=== クレデンシャルを使用してクラスタをペアリング

一方のクラスタの MVIP を使用してもう一方のクラスタとの接続を確立することにより、リアルタイムレプリケーション用に 2 つのクラスタをペアリングできます。この方法を使用するには、両方のクラスタに対するクラスタ管理者アクセスが必要です。

クラスタをペアリングする前に、クラスタ管理者のユーザ名とパスワードを使用してクラスタアクセスを認証します。

MVIP がわからない場合やクラスタへのアクセスが許可されていない場合は、ペアリングキーを生成し、そのキーを使用して 2 つのクラスタをペアリングできます。手順については、を参照してください  clusters with a pairing key。

.手順
. ローカルクラスタを含む vCenter から、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ クラスタペア * （ Cluster Pairs * ） ] サブタブを選択します。
. 「 * クラスタペアリングの作成」を選択します。
. 次のいずれかを選択します。
+
** *登録クラスタ*：ペアリングするリモートクラスタがElement vCenterプラグインの同じインスタンスで制御されている場合は、このオプションを選択します。
** * Credentialed Cluster *：リモートクラスタにElement vCenterプラグインの外部で設定された既知のクレデンシャルがある場合は、このオプションを選択します。


. 「 Registered Cluster 」を選択した場合は、使用可能なクラスタのリストからクラスタを選択し、「 * Pair * 」をクリックします。
. Credentialed Cluster * を選択した場合は、次の手順を実行します。
+
.. リモートクラスタの MVIP アドレスを入力します。
.. クラスタ管理者のユーザ名を入力します。
.. クラスタ管理者のパスワードを入力します。
.. 「 * ペアリングを開始」を選択します。


. タスクが完了してクラスタペアページが表示されたら、クラスタペアが接続されていることを確認します。
. （オプション）リモートクラスタで、 * NetApp Element Management* > * Protection * > * Cluster Pairs * を選択するか、 Element Web UI を使用してクラスタペアが接続されていることを確認します。




=== ペアリングキーを使用してクラスタをペアリングします

ローカルクラスタにはクラスタ管理者としてアクセスできるが、リモートクラスタにはアクセスできない場合は、ペアリングキーを使用してクラスタをペアリングします。ローカルクラスタで生成したペアリングキーをリモートサイトのクラスタ管理者に安全な方法で送信して接続を確立し、リアルタイムレプリケーション用にクラスタをペアリングします。

この手順では、ローカルサイトとリモートサイトで vCenter を使用し、 2 つのクラスタをペアリングする方法について説明します。vCenter Plug-in で制御されないクラスタの場合は、代わりにを使用することもできます https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_cluster_using_pairing_key.html["クラスタペアリングを開始または完了します"] Element Web UI を使用

.手順
. ローカルクラスタを含む vCenter から、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ クラスタペア * （ Cluster Pairs * ） ] サブタブを選択します。
. 「 * クラスタペアリングの作成」を選択します。
. アクセスできないクラスタを選択します。
. [* キーの生成 * ] を選択します。
+

NOTE: この操作により、ペアリング用のテキストキーが生成され、ローカルクラスタにクラスタペアが未設定の状態で作成されます。手順を完了しない場合は、クラスタペアを手動で削除する必要があります。

. クラスタペアリングキーをクリップボードにコピーします。
. [ 閉じる（ Close ） ] を選択します。
. このペアリングキーをリモートクラスタサイトのクラスタ管理者に渡します。
+

NOTE: クラスタペアリングキーには、リモートレプリケーション用にボリューム接続を許可するための MVIP のバージョン、ユーザ名、パスワード、およびデータベース情報が含まれています。このキーの取り扱いには十分に注意し、ユーザ名やパスワードが誤って外部に漏れたり不正に使用されたりしないように適切に管理してください。

+

IMPORTANT: ペアリングキーの文字はいっさい変更しないでください。キーが変更されると無効になります。

. リモートクラスタを含む vCenter から、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

+

NOTE: Element UI を使用してペアリングを実行することもできます。

. [ クラスタペア * （ Cluster Pairs * ） ] サブタブを選択します。
. 「完全なクラスタペアリング」を選択します。
+

NOTE: ロード中のスピナーアイコンが消えてから次の手順に進みます。ペアリングプロセス中に予期しないエラーが発生した場合は、ローカルクラスタとリモートクラスタで未設定のクラスタペアがあれば手動で削除し、ペアリングをもう一度実行してください。

. ローカルクラスタのペアリングキーを * クラスタペアリングキー * フィールドに貼り付けます。
. 「 * Pair Cluster * 」を選択します。
. タスクが完了して「 * クラスタペア * 」ページが表示されたら、クラスタペアが接続されていることを確認します。
. クラスタペアが接続されていることを確認するには、リモートクラスタで * NetApp Element Management * > * Protection * を選択するか、 Element UI を使用します。




=== クラスタペアの接続を検証

クラスタペアリングが完了したら、クラスタペアの接続を検証して、レプリケーションが成功したかどうかを確認できます。

.手順
. ローカルクラスタで、 * Data Protection * > * Cluster Pairs * を選択します。
. クラスタペアが接続されていることを確認します。
. ローカルクラスタと * クラスタペア * ウィンドウに戻り、クラスタペアが接続されていることを確認してください。




== ボリュームをペアリング

クラスタペアのクラスタ間の接続を確立したら、一方のクラスタのボリュームをもう一方のクラスタのボリュームとペアリングできます。

次のいずれかの方法でボリュームをペアリングできます。

*  volumes using known credentials：両方のクラスタに既知のクレデンシャルを使用します
*  volumes using a pairing key：ペアリングキーは、ソースクラスタでしかクラスタのクレデンシャルを使用できない場合に使用します。
*  target volumes and pair them with local volumes：両方のクラスタのクレデンシャルがわかっている場合は、リモートクラスタにレプリケーションターゲットボリュームを作成してソースクラスタとペアリングします。


ボリュームペアリング関係を確立したら、どちらのボリュームをレプリケーションターゲットにするかを指定する必要があります。

*  a replication source and target to paired volumes


.必要なもの
* クラスタペアのクラスタ間の接続を確立しておく必要があります。
* ペアリングするクラスタの一方または両方に対するクラスタ管理者権限が必要です。




=== クレデンシャルを使用してボリュームをペアリング

ローカルボリュームをリモートクラスタの別のボリュームとペアリングできます。この方法は、ボリュームをペアリングする両方のクラスタにクラスタ管理者としてアクセスできる場合に使用します。リモートクラスタのボリュームのボリューム ID を使用して接続を開始します。

.作業を開始する前に
* リモートクラスタのクラスタ管理者のクレデンシャルが必要です。
* 該当するボリュームを含むクラスタがペアリングされていることを確認します。
* このプロセスで新しいボリュームを作成する場合を除き、リモートボリュームの ID が必要です。
* ローカルボリュームをソースにする場合は、ボリュームのアクセスモードが読み取り / 書き込みに設定されていることを確認してください。


.手順
. ローカルクラスタを含む vCenter から、 * NetApp Element 管理 * > * 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、ペアリングするボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * Volume Pairing * （ボリュームペアリング）」を選択
. 次のいずれかを選択します。
+
** * ボリュームの作成 * ：リモートクラスタにレプリケーションターゲットボリュームを作成する場合に選択します。この方法は、Element vCenterプラグインで制御されているリモートクラスタでのみ使用できます。
** *ボリュームの選択*：ターゲットボリュームを含むリモートクラスタがElement vCenterプラグインで制御されている場合に選択します。
** *ボリュームID *：ターゲットボリュームを含むリモートクラスタに、Element vCenterプラグイン以外の設定で設定された既知のクレデンシャルがある場合に選択します。


. レプリケーションモードの選択：
+
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. ペアリングモードオプションとして * Volume Creation * を選択した場合は、次の手順を実行します。
+
.. ドロップダウンリストからペアクラスタを選択します。
+

NOTE: この操作により、次の手順で選択する、クラスタで使用可能なアカウントが設定されます。

.. レプリケーションターゲットボリュームを含むターゲットクラスタ上のアカウントを選択します。
.. レプリケーションターゲットボリューム名を入力します。
+

NOTE: このプロセスではボリュームサイズを調整できません。



. ペアリングモードオプションとして * Volume Selection * を選択した場合は、次の手順を実行します。
+
.. ペアクラスタを選択
+

NOTE: 次の手順で選択する、クラスタ上の使用可能なボリュームが表示されます。

.. （オプション）ボリュームペアリングでリモートボリュームをターゲットとして設定する場合は、 * リモートボリュームをレプリケーションターゲットに設定 * オプションを選択します。ローカルボリュームが読み取り / 書き込みに設定されている場合、そのボリュームがペアのソースになります。
+

IMPORTANT: レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。レプリケーションターゲットには新しいボリュームを使用することを推奨します。

+

NOTE: レプリケーションのソースとターゲットは、あとから * Volumes * > * Actions * > * Edit * のペアリングプロセスで割り当てることもできます。ペアリングを完了するには、ソースとターゲットを割り当てる必要があります。

.. 使用可能なボリュームのリストからボリュームを選択します。


. ペアリングモードオプションとして * Volume ID * を選択した場合は、次の手順を実行します。
+
.. ドロップダウンリストからペアクラスタを選択します。
.. クラスタがプラグインに登録されていない場合は、クラスタ管理者のユーザ ID とクラスタ管理者のパスワードを入力します。
.. ボリューム ID を入力します。
.. リモートボリュームをボリュームペアリングのターゲットとして設定する場合は、 * リモートボリュームをレプリケーションターゲットに設定 * オプションを選択します。ローカルボリュームが読み取り / 書き込みに設定されている場合、そのボリュームがペアのソースになります。
+

IMPORTANT: レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。レプリケーションターゲットには新しいボリュームを使用することを推奨します。

+

NOTE: レプリケーションのソースとターゲットは、あとから * Volumes * > * Actions * > * Edit * のペアリングプロセスで割り当てることもできます。ペアリングを完了するには、ソースとターゲットを割り当てる必要があります。



. 「 * Pair * （ペアリング）」を選択
+

NOTE: ペアリング操作を確定すると、 2 つのクラスタでボリュームを接続するプロセスが開始されます。ペアリングプロセスの実行中、ボリュームペアページのボリュームステータス列に進捗状況のメッセージが表示されます。

+

NOTE: レプリケーションターゲットにするボリュームをまだ割り当てていない場合、ペアリングの設定は完了していません。ソースとターゲットが割り当てられるまで、ボリュームペアには PausedMisconfigured と表示されます。ボリュームペアリングを完了するには、ソースとターゲットを割り当てる必要があります。

. いずれかのクラスタで、 * Protection * > * Volume Pairs * を選択します。
. ボリュームペアリングのステータスを確認します。




=== ペアリングキーを使用してボリュームをペアリングします

ペアリングキーを使用して、ローカルボリュームをリモートクラスタの別のボリュームとペアリングできます。この方法は、一方のクラスタにしかクラスタ管理者としてアクセスできない場合に使用します。ペアリングキーを生成し、そのキーをリモートクラスタで使用してボリュームをペアリングします。

.作業を開始する前に
* 該当するボリュームを含むクラスタがペアリングされていることを確認します。
* * ベストプラクティス * ：ソースボリュームを読み取り / 書き込みに、ターゲットボリュームをレプリケーションターゲットに設定します。ターゲットボリュームは、データが格納されておらず、かつサイズ、 512e 、 QoS などの特性がソースボリュームとまったく同じである必要があります。レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。


この手順では、ローカルサイトとリモートサイトで vCenter を使用し、 2 つのボリュームをペアリングする方法について説明します。vCenter Plug-in で制御されていないボリュームについては、 Element Web UI を使用してボリュームのペアリングを開始または完了することができます。

Element Web UI からボリュームのペアリングを開始または完了する手順については、を参照してください https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_volumes_using_a_pairing_key.html["NetApp Element ソフトウェアのドキュメント"^]。


NOTE: ボリュームペアリングキーには、暗号化されたボリューム情報が格納されており、機密情報が含まれている場合があります。このキーは必ず安全な方法で共有してください。

.手順
. ローカルクラスタを含む vCenter から、 * NetApp Element 管理 * > * 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、ペアリングするボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * Volume Pairing * （ボリュームペアリング）」を選択
. アクセスできないクラスタを選択します。
. レプリケーションモードの選択：
+
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. [* キーの生成 * ] を選択します。
+

NOTE: この操作により、ペアリング用のテキストキーが生成され、ローカルクラスタにボリュームペアが未設定の状態で作成されます。この処理を行わない場合は、ボリュームペアを手動で削除する必要があります。

. ペアリングキーをクリップボードにコピーします。
. [ 閉じる（ Close ） ] を選択します。
. このペアリングキーをリモートクラスタサイトのクラスタ管理者に渡します。
+

NOTE: ボリュームペアリングキーの取り扱いには十分に注意し、誤って外部に漏れたり不正に使用されたりしないように適切に管理してください。

+

IMPORTANT: ペアリングキーの文字はいっさい変更しないでください。キーが変更されると無効になります。

. リモートクラスタを含む vCenter から、 * NetApp Element 管理 * > * 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、ペアリングするボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * Volume Pairing * （ボリュームペアリング）」を選択
. 「完全なクラスタペアリング」を選択します。
. もう一方のクラスタのペアリングキーを * ペアリングキー * ボックスに貼り付けます。
. 「完全ペアリング」を選択します。
+

NOTE: ペアリング操作を確定すると、 2 つのクラスタでボリュームを接続するプロセスが開始されます。ペアリングプロセスの実行中、ボリュームペアページのボリュームステータス列に進捗状況のメッセージが表示されます。ペアリングプロセス中に予期しないエラーが発生した場合は、ローカルクラスタとリモートクラスタで未設定のクラスタペアがあれば手動で削除し、ペアリングをもう一度実行してください。

+

IMPORTANT: レプリケーションターゲットにするボリュームをまだ割り当てていない場合、ペアリングの設定は完了していません。ソースとターゲットが割り当てられるまで、ボリュームペアには「 PausedMisconfigured 」と表示されます。ボリュームペアリングを完了するには、ソースとターゲットを割り当てる必要があります。

. いずれかのクラスタで、 * Protection * > * Volume Pairs * を選択します。
. ボリュームペアリングのステータスを確認します。
+

NOTE: ペアリングキーを使用してペアリングされたボリュームは、リモート側でペアリングプロセスが完了してから表示されます。





=== ターゲットボリュームを作成し、ローカルボリュームとペアリングします

2 つ以上のローカルボリュームをリモートクラスタの関連するターゲットボリュームとペアリングできます。このプロセスでは、選択した各ローカルソースボリュームに対して、リモートクラスタにレプリケーションターゲットボリュームが作成されます。この方法は、ボリュームをペアリングする両方のクラスタにクラスタ管理者としてアクセスでき、リモートクラスタがプラグインで制御されている場合に使用します。

リモートクラスタの各ボリュームのボリューム ID を使用して接続が開始されます。

.作業を開始する前に
* リモートクラスタのクラスタ管理者のクレデンシャルがあることを確認しておきます。
* 該当するボリュームを含むクラスタがプラグインを使用してペアリングされていることを確認します。
* リモートクラスタがプラグインで制御されていることを確認してください。
* 各ローカルボリュームのアクセスモードが読み取り / 書き込みに設定されていることを確認してください。


.手順
. ローカルクラスタを含む vCenter から、 * NetApp Element 管理 * > * 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、ペアリングするボリュームを複数選択します。
. [ * アクション * ] を選択します。
. 「 * Volume Pairing * （ボリュームペアリング）」を選択
. * レプリケーションモード * ：
+
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. ドロップダウンリストからペアクラスタを選択します。
. レプリケーションターゲットボリュームを含むターゲットクラスタ上のアカウントを選択します。
. （オプション）ターゲットクラスタの新しいボリューム名に使用するプレフィックスまたはサフィックスを入力します。
+

NOTE: 変更した名前のサンプルボリュームが表示されます。

. 「 * ペアの作成 * 」を選択します。
+

NOTE: ペアリング操作を確定すると、 2 つのクラスタでボリュームを接続するプロセスが開始されます。ペアリングプロセスの実行中、ボリュームペアページのボリュームステータス列に進捗状況のメッセージが表示されます。プロセスが完了すると、リモートクラスタに新しいターゲットボリュームが作成されて接続されます。

. いずれかのクラスタで、 * Protection * > * Volume Pairs * を選択します。
. ボリュームペアリングのステータスを確認します。




=== ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます

ボリュームのペアリング中にレプリケーションターゲットにするボリュームを割り当てていない場合、設定は完了していません。この手順を使用して、ソースボリュームとそのレプリケーションターゲットボリュームを割り当てることができます。ボリュームペアのどちらのボリュームをレプリケーションのソースまたはターゲットにしてもかまいません。

この手順を使用して、ソースボリュームが使用できなくなったときにソースボリュームからリモートターゲットボリュームにデータをリダイレクトすることもできます。

ソースボリュームとターゲットボリュームを含むクラスタへのアクセス権が必要です。

この手順では、ローカルサイトとリモートサイトで vCenter を使用し、 2 つのクラスタ間にソースボリュームとレプリケーションボリュームを割り当てる方法について説明します。vCenter Plug-in で制御されていないボリュームについては、別の方法で制御することもできます https://docs.netapp.com/us-en/element-software/storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html["ソースボリュームまたはレプリケーションボリュームを割り当てます"] Element Web UI を使用

レプリケーションソースボリュームには読み取り / 書き込みのアカウントアクセスが設定されます。レプリケーションターゲットボリュームには、レプリケーションソースのみが読み取り / 書き込みアクセスできます。

* ベストプラクティス * ：ターゲットボリュームにはデータを格納せず、サイズ、 512e 、 QoS などをソースボリュームとまったく同じにします。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。

.手順
. vCenter Server の * NetApp Element Management * 拡張ポイントで、レプリケーションソースとして使用するペアリングされたボリュームが含まれているクラスタを選択します。
. NetApp Element Management*>* Management* を選択します。
. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、編集するボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * 編集 * 」を選択します。
. [ アクセス ] ドロップダウンリストから、 [*Read/Write *] を選択します。
+

IMPORTANT: ソースとターゲット原因の割り当てを逆にしている場合、新しいレプリケーションターゲットが割り当てられるまでボリュームペアには PausedMisconfigured と表示されます。アクセスを変更すると、ボリュームレプリケーションが一時停止し、データの転送が中止されます。両方のサイトでこれらの変更を調整したことを確認してください。

. 「 * OK 」を選択します。
. NetApp Element Management * 拡張ポイントで、レプリケーションターゲットとして使用するペアリングされたボリュームが含まれているクラスタを選択します。
. NetApp Element Management*>* Management* を選択します。
. [* Volumes （ボリューム） ] サブタブを選択します。
. アクティブ * ビューで、編集するボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * 編集 * 」を選択します。
. [*Access*] ドロップダウン・リストで '[*Replication Target*] を選択します
+

IMPORTANT: レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。レプリケーションターゲットには新しいボリュームを使用することを推奨します。

. 「 * OK 」を選択します。




== ボリュームレプリケーションを検証

ボリュームがレプリケートされたら、ソースボリュームとターゲットボリュームがアクティブになっていることを確認する必要があります。状態が Active の場合は、ボリュームがペアリングされ、ソースボリュームからターゲットボリュームにデータが送信されて同期されています。

.手順
. ペアリング内のいずれかのクラスタで、 * NetApp Element Management* > * Protection* を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ボリュームペア * （ Volume Pairs * ） ] サブタブを選択します。
. ボリュームのステータスが Active であることを確認します。




== レプリケーション後にボリューム関係を削除

レプリケーションが完了してボリュームペアリング関係が不要になったら、ボリューム関係を削除できます。

を参照してください  a volume pair。



== ボリューム関係を管理

レプリケーションの一時停止、ボリュームペアリングの反転、レプリケーションモードの変更、ボリュームペアの削除、クラスタペアの削除など、さまざまな方法でボリューム関係を管理できます。

*  replication
*  the mode of replication
*  a volume pair
*  a cluster pair




=== レプリケーションを一時停止

ボリュームペアのプロパティを編集して、レプリケーションを手動で一時停止することができます。

.手順
. NetApp Element Management*>* Protection* を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ボリュームペア * （ Volume Pairs * ） ] サブタブを選択します。
. 編集するボリュームペアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * 編集 * 」を選択します。
. レプリケーションプロセスを手動で一時停止または開始します。
+

IMPORTANT: ボリュームレプリケーション原因を手動で一時停止または再開すると、データの転送が中止または再開されます。両方のサイトでこれらの変更を調整したことを確認してください。

. 「変更を保存」を選択します。




=== レプリケーションのモードを変更します

ボリュームペアのプロパティを編集して、ボリュームペア関係のレプリケーションモードを変更することができます。

.手順
. NetApp Element Management*>* Protection* を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ボリュームペア * （ Volume Pairs * ） ] サブタブを選択します。
. 編集するボリュームペアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * 編集 * 」を選択します。
. 新しいレプリケーションモードを選択します。
+

IMPORTANT: レプリケーションモードの変更はすぐに反映されます。両方のサイトでこれらの変更を調整したことを確認してください。

+
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. 「変更を保存」を選択します。




=== ボリュームペアを削除する

2 つのボリューム間のペア関係を解除するには、ボリュームペアを削除します。

この手順では、ローカルサイトとリモートサイトで vCenter を使用し、 2 つのボリュームのペアリング関係を削除する方法について説明します。

vCenter Plug-in で制御されていないボリュームについては、代わりにを使用することもできます link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_volume_relationship_after_replication.html["ボリュームペアの削除"] Element Web UI を使用

.手順
. NetApp Element Management*>* Protection* を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ボリュームペア * （ Volume Pairs * ） ] サブタブを選択します。
. 削除するボリュームペアを 1 つ以上選択します。
. [ * アクション * ] を選択します。
. 「 * 削除」を選択します。
. 各ボリュームペアの詳細を確認します。
+

NOTE: プラグインで管理されていないクラスタの場合、ローカルクラスタ側のボリュームペア関係のみが削除されます。ペアリング関係を完全に削除するには、リモートクラスタ側のボリュームペア関係を手動で削除する必要があります。

. （プラグインで管理されるクラスタのオプション） * Change Replication Target Access to * のチェックボックスを選択し、レプリケーションターゲットボリュームの新しいアクセスモードを選択します。この新しいアクセスモードは、ボリュームペアリング関係の削除後に適用されます。
. 「 * はい * 」を選択します。




=== クラスタペアを削除する

ローカルサイトとリモートサイトで vCenter を使用して、 2 つのクラスタ間のクラスタペアリング関係を削除できます。クラスタペアリング関係を完全に削除するには、ローカルとリモートの両方のクラスタからクラスタペアを削除する必要があります。

vCenter Plug-in を使用してクラスタペアを削除できます

vCenter Plug-in で制御されないクラスタの場合は、代わりにを使用することもできます link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_cluster_pair.html["クラスタペアの削除"] Element Web UI を使用

.手順
. NetApp Element Management*>* Protection* を選択します。
. [ クラスタペア * （ Cluster Pairs * ） ] サブタブを選択します。
. 削除するクラスタペアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 「 * 削除」を選択します。
. 操作を確定します。
+

NOTE: この操作では、ローカルクラスタ側のクラスタペアのみが削除されます。ペアリング関係を完全に削除するには、リモートクラスタ側のクラスタペア関係を手動で削除する必要があります。

. クラスタペアリングのリモートクラスタで同じ手順を繰り返します。




== ボリュームペアリングに関するメッセージと警告

NetApp Element 管理の設定ポイントで、保護タブのボリュームペアのページで、ペアリングされているボリュームまたはペアリング処理中のボリュームの情報を確認できます。

ペアリングと進捗状況を示すメッセージがボリュームステータス列に表示されます。

*  pairing messages
*  pairing warnings




=== ボリュームペアリングに関するメッセージ

NetApp Element の管理設定ポイントから、保護タブのボリュームペアページで最初のペアリングプロセス中に表示されるメッセージを確認できます。これらのメッセージはボリュームステータス列に表示され、ペアリングのソースとターゲットの両方の端に表示されます。

* * PausedDisconnected * ：ソースレプリケーションまたは同期 RPC がタイムアウトしました。リモートクラスタへの接続が失われました。クラスタへのネットワーク接続を確認してください。
* * ResumingConnected ** ：リモートレプリケーションの同期がアクティブになりました。同期プロセスが開始され、データを待っています。
* * ResumingRRSync ** ：ペアクラスタにボリュームメタデータの Single Helix コピーを作成しています。
* * ResumingLocalSync** ：ペアクラスタにボリュームメタデータの Double Helix コピーを作成中です。
* * データ転送の再開 ** ：データ転送が再開されました。
* * アクティブ * ：ボリュームがペアリングされ、ソースボリュームからターゲットボリュームにデータが送信されて同期されています。
* * アイドル * ：レプリケーションアクティビティが実行されていません。


* この処理はターゲットボリュームで開始され、ソースボリュームには表示されない場合があります。



=== ボリュームペアリングに関する警告

NetApp Element 管理設定ポイントから保護タブのボリュームペアページでボリュームをペアリングすると、警告メッセージを確認できます。これらのメッセージはボリュームステータス列に表示され、ペアリングのソースとターゲットの両方の端に表示されます。

特に記載がないかぎり、これらのメッセージはペアリングのソースとターゲットの両方に表示されます。

* * PausedClusterFull * ：ターゲットクラスタがいっぱいのため、ソースレプリケーションと一括データ転送を続行できません。このメッセージは、ペアのソース側にのみ表示されます。
* * PausedExceededMaxSnapshotCount * ：ターゲットボリュームにすでに最大数の Snapshot があり、追加の Snapshot をレプリケートできません。
* * PausedManual* ：ローカルボリュームが手動で一時停止されています。レプリケーションを再開するには、一時停止を解除する必要があります。
* * PausedManualRemote *: リモートボリュームが手動で一時停止されています。レプリケーションを再開するには、リモートボリュームの一時停止を手動で解除する必要があります。
* * PausedMisconfigured * ：アクティブなソースとターゲットを待機している場合レプリケーションを再開するには手動での対応が必要です。
* * PausedQoS * ：ターゲット QoS で受信 IO を維持できませんでした。レプリケーションは自動で再開されます。このメッセージは、ペアのソース側にのみ表示されます。
* *PausedSlowLink*: 低速リンクが検出され、レプリケーションが停止しました。レプリケーションは自動で再開されます。このメッセージは、ペアのソース側にのみ表示されます。
* * PausedVolumeSizeMismatch* ：ターゲットボリュームがソースボリュームよりも小さくなっています。
* * PausedXCopy * ：ソースボリュームに対して SCSI XCOPY コマンドが実行されています。このコマンドは、レプリケーションを再開する前に完了している必要があります。このメッセージは、ペアのソース側にのみ表示されます。
* *StoppedMisconfigured *: 永続的な設定エラーが検出されました。リモートボリュームがパージされたかペアが解除されました。対処方法はありません。新しいペアリングを確立する必要があります。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

