---
sidebar: sidebar 
permalink: vcp_reference_reports_alert_errors.html 
summary: 次に、NetApp Element Plug-in for VMware vCenter Serverのレポートページを使用して、クラスタが正常に稼働していることを示す情報、警告、またはエラーのリストを示します。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= システムアラートのリスト
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
各アラートについてエラーコードが報告されるため、アラートが発生したシステムのコンポーネントおよびアラートが生成された理由を確認できます。プラグイン拡張ポイントを使用して、エラーコードを確認できます。

* Element vCenterプラグイン5.0以降では、* NetApp Remote Plugin > Management > Reporting > Alerts *の順に選択します。
* Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Reporting > Alerts *の順に選択します。


以下に、各種のシステムアラートの一覧を示します。

* * authenticationServiceFault*
+
1 つ以上のクラスタノードの認証サービスが正常に機能していません。

+
ネットアップサポートにお問い合わせください。

* * 利用可能な VirtualNetworkIPAddressesLow *
+
IP アドレスブロック内の仮想ネットワークアドレスの数が少なくなっています。

+
この問題を解決するには、仮想ネットワークアドレスのブロックに IP アドレスを追加してください。

* * blockClusterFull *
+
単一ノードの損失をサポートするのに十分なブロックストレージの空き容量がありません。クラスタフルのレベルの詳細については、 GetClusterFullThreshold API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。

+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。


+
この問題を解決するには、ボリュームをパージまたは削除するか、ストレージクラスタに別のストレージノードを追加してください。

* * ブロックが劣化しました *
+
障害により、ブロックデータの完全なレプリケートが行われなくなりました。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
アクセス可能なブロックデータの完全なコピーは 2 つだけです。



 a| 
エラー
 a| 
アクセス可能なブロックデータの完全なコピーは 1 つだけです。



 a| 
重要
 a| 
ブロックデータの完全なコピーにはアクセスできません。

|===
+
* 注意： * 警告ステータスは、トリプル Helix システムでのみ発生します。

+
この問題を解決するには、オフラインのノードまたはブロックサービスをリストアするか、ネットアップサポートにお問い合わせください。

* * blockServiceTooFull*
+
ブロックサービスが大量のスペースを使用しています。

+
この問題を解決するには、プロビジョニング済み容量を追加してください。

* * ブロックされたもの *
+
ブロックサービスが正常でないことが検出されました：

+
** 重大度 = 警告：対処は行われません。この警告期間は、 cTimeUntilBSIsKilledMSec = 330000 ミリ秒で期限切れになります。
** 重大度 = エラー：データの運用停止処理が自動的に実行され、他の正常なドライブにデータが再レプリケートされます。
** 重大度 = 重大：複数のノードで障害ブロックサービスが発生していますが、レプリケーション数以上になっています（ Double Helix の場合は 2 ）。データを使用できないため、ビンの同期が完了しません。


+
ネットワーク接続の問題とハードウェアエラーを確認します。特定のハードウェアコンポーネントで障害が発生した場合は、それ以外の障害が発生します。この障害は、ブロックサービスにアクセスできるかサービスが運用停止されると解消されます。

* * BmcSelfTestFailed*
+
ベースボード管理コントローラ（BMC）のセルフテストに失敗しました。

+
ネットアップサポートにお問い合わせください。

+
Element 12.5以降へのアップグレード中は、を使用します `BmcSelfTestFailed` BMCにすでに障害が発生しているノード、またはアップグレード中にノードのBMCに障害が発生した場合、障害は生成されません。アップグレード中にセルフテストに失敗したBMCは問題 Aになります `BmcSelfTestFailed` クラスタ全体のアップグレード完了後に発生する警告。

* * clockSkewExceedsFaultThreshold *
+
クラスタマスターとトークンを提供しているノードの間の時間差が推奨されるしきい値を超えています。ストレージクラスタは、ノード間の時間スキューを自動的に修正できません。

+
この問題を解決するには、インストール時のデフォルトではなく、使用するネットワーク内の NTP サーバを使用してください。内部の NTP サーバを使用している場合は、ネットアップサポートにお問い合わせください。

* * clusterCannotSync*
+
スペース不足の状態にあり、オフラインのブロックストレージドライブ上のデータをアクティブなドライブと同期できません。

+
この問題を解決するには、ストレージを追加してください。

* * clusterFull *
+
ストレージクラスタ内の空きストレージスペースが不足しています。

+
この問題を解決するには、ストレージを追加してください。

* * clusterIOPSAreOverProvised*
+
クラスタの IOPS がオーバープロビジョニングされています。QoS の最小 IOPS の合計が、クラスタの想定 IOPS を上回っています。すべてのボリュームで同時に最小 QoS を維持することができません。

+
この問題を解決するには、ボリュームの最小 QoS IOPS 設定を引き下げてください。

* * CpuThermalEventThreshold *
+
1つ以上のCPUのCPU温度イベントの数が、設定されたしきい値を超えています。

+
10分以内に新しいCPU温度イベントが検出されない場合、警告は自動的に解決します。

* *disableDriveSecurityFailed*
+
クラスタはドライブのセキュリティ（保存中のデータの暗号化）を有効にするようには設定されていませんが、少なくとも 1 つのドライブでドライブのセキュリティが有効になっているため、それらのドライブでドライブのセキュリティを無効にできませんでした。この障害は重大度が「 Warning 」で記録されます。

+
この問題を解決するには、ドライブのセキュリティを無効にできなかった理由について障害の詳細を確認してください。考えられる原因は次のとおりです。

+
** 暗号化キーを取得できませんでした。キーまたは外部キーサーバへのアクセスに関する問題を調査してください。
** ドライブで無効化処理に失敗した場合は、間違ったキーが取得されていないかどうかを確認してください。


+
どちらでもない場合は、ドライブの交換が必要となる可能性があります。

+
正しい認証キーを指定してもセキュリティが無効にならないドライブに対して、リカバリを試みることができます。この処理を実行するには、ドライブの状態を Available に変更してシステムから取り外し、ドライブで完全消去を実行してから Active に戻します。

* * 接続解除されたクラスタペア *
+
クラスタペアが切断されているか、正しく設定されていません。

+
クラスタ間のネットワーク接続を確認してください。

* * disconnectedRemoteNode * を実行します
+
リモートノードが切断されているか、正しく設定されていません。

+
ノード間のネットワーク接続を確認してください。

* * 切断された SnapMirrorEndpoint *
+
リモート SnapMirror エンドポイントが切断されているか、正しく設定されていません。

+
クラスタとリモート SnapMirrorEndpoint の間のネットワーク接続を確認してください。

* * 走行可能 *
+
クラスタ内に利用可能なドライブがあります。通常は、すべてのクラスタにすべてのドライブが追加されており、利用可能な状態のドライブはありません。この問題が予期せずに発生する場合は、ネットアップサポートにお問い合わせください。

+
この問題を解決するには、使用可能なドライブをすべてストレージクラスタに追加してください。

* * driveFailed *
+
次のいずれかの状態のドライブで障害が発生すると、クラスタはこのエラーを返します。

+
** ドライブマネージャがドライブにアクセスできません。
** スライスサービスまたはブロックサービスで障害が発生した回数が多すぎます。おそらくドライブの読み取りまたは書き込みの失敗が原因で再起動できません。
** ドライブがありません。
** ノードのマスターサービスにアクセスできません（ノード内のすべてのドライブが見つからないか障害状態であるとみなされます）。
** ドライブがロックされており、そのドライブの認証キーを取得できません。
** ドライブがロックされているためロック解除処理が失敗します。


+
この問題を解決するには：

+
** ノードのネットワーク接続を確認してください。
** ドライブを交換します。
** 認証キーが使用可能であることを確認します。


* * driveHealthFault *
+
ドライブが SMART ヘルスチェックに失敗したため、ドライブの機能が低下しました。この障害には、 Critical 重大度レベルがあります。

+
** シリアル付きドライブ： < シリアル番号 > 、スロット： < ノードスロット >< ドライブスロット > 、 SMART 全体のヘルスチェックに失敗しました。


+
この問題を解決するには、ドライブを交換してください。

* * driveWearFault *
+
ドライブの残存寿命がしきい値を下回っていますが、まだ機能しています。この障害には、重大度レベルとして「重大」と「警告」の 2 つのレベルがあります。

+
** シリアル付きドライブ： <serial number> in slot ： <node slot><drive slot> には、重大な摩耗度レベルがあります。
** Serial Number > in slot ： < ノードスロット >< ドライブスロット > のドライブの摩耗リザーブが少ない。


+
この問題を解決するには、ドライブをすぐに交換してください。

* * duplicateClusterMasterCandidates *
+
ストレージクラスタマスターの候補が複数検出されました。

+
ネットアップサポートにお問い合わせください。

* * enableDriveSecurityFailed*
+
クラスタはドライブのセキュリティ（保存中のデータの暗号化）を要求するように設定されていますが、少なくとも 1 つのドライブでセキュリティを有効にできませんでした。この障害は重大度が「 Warning 」で記録されます。

+
この問題を解決するには、ドライブのセキュリティを有効にできなかった理由について障害の詳細を確認してください。考えられる原因は次のとおりです。

+
** 暗号化キーを取得できませんでした。キーまたは外部キーサーバへのアクセスに関する問題を調査してください。
** ドライブで有効化処理に失敗した場合は、間違ったキーが取得されていないかどうかを確認してください。どちらでもない場合は、ドライブの交換が必要となる可能性があります。


+
正しい認証キーを指定してもセキュリティが有効にならないドライブに対して、リカバリを試みることができます。この処理を実行するには、ドライブの状態を Available に変更してシステムから取り外し、ドライブで完全消去を実行してから Active に戻します。

* * ensembleDegraded *
+
1 つ以上のアンサンブルノードで、ネットワーク接続または電源が失われました。

+
この問題を解決するには、ネットワーク接続または電源を復旧してください。

* * 例外 *
+
通常の障害以外の障害が報告されました。これらの障害は、障害キューから自動的に消去されることはありません。

+
ネットアップサポートにお問い合わせください。

* * 失敗した SpaceTooFull *
+
ブロックサービスがデータ書き込み要求に応答していません。スライスサービスが失敗した書き込みを格納するためのスペースが不足します。

+
この問題を解決するには、書き込みを正常に続行し、失敗した書き込みのスペースをスライスサービスからフラッシュできるように、ブロックサービス機能をリストアしてください。

* * fanSensor *
+
ファンセンサーに障害が発生しているか、ファンセンサーがありません。

+
この問題を解決するには、障害が発生したハードウェアを交換してください。

* * fibreChannelAccessDegraded *
+
Fibre Channel ノードが自身のストレージ IP でストレージクラスタ内の他のノードに一定期間応答していません。この状態になると、ノードは応答していないと判断され、クラスタ障害が生成されます。

+
ネットワーク接続を確認してください。

* * fibreChannelAccessUnavailable*
+
すべての Fibre Channel ノードが応答していません。ノード ID が表示されます。

+
ネットワーク接続を確認してください。

* * fibreChannelActiveIxL *
+
iXL Nexus 数は、サポートされるファイバチャネルノードあたりのアクティブセッション数が最大 8000 に近づいています。

+
** ベストプラクティスの上限は 5500 です。
** 警告の上限は 7500 です。
** 上限（必須ではない）は 8192 です。


+
この問題を解決するには、 iXL Nexus の数をベストプラクティスの上限である 5500 未満に減らしてください。

* * fibreChannelConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** PCI スロットに予期しないファイバチャネルポートがあります。
** 想定外の Fibre Channel HBA モデルが使用されています。
** Fibre Channel HBA のファームウェアに問題があります。
** Fibre Channel ポートがオンラインではありません。
** Fibre Channel パススルーを設定している永続的な問題があります。


+
ネットアップサポートにお問い合わせください。

* * fibreChannelIOPS*
+
合計 IOPS 数がクラスタ内の Fibre Channel ノードの IOPS 制限に近づいています。制限は次のとおりです。

+
** FC0025 ： 450 、 000 IOPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）
** FCN001 ： 625K OPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）。


+
この問題を解決するには、使用可能なすべての Fibre Channel ノードに負荷を分散してください。

* * fibreChannelStaticIxL *
+
iXL Nexus の数は、サポートされるファイバチャネルノードあたりの静的セッションの上限である 16000 に近づいています。

+
** ベストプラクティスの上限は 11000 です。
** 警告制限は 15000 です。
** 最大制限（強制）は 16384 です。


+
この問題を解決するには、 iXL Nexus の数をベストプラクティスの上限である 11000 未満に減らしてください。

* * fileSystemCapacityLow *
+
いずれかのファイルシステムでスペースが不足しています。

+
この問題を解決するには、ファイルシステムに容量を追加してください。

* * fileSystemIsReadOnly*
+
ファイルシステムが読み取り専用モードに移行しました。

+
ネットアップサポートにお問い合わせください。

* * FipsDrivesMismatch *
+
FIPS 対応ストレージノードに FIPS 非対応ドライブが挿入されているか、 FIPS 非対応ストレージノードに FIPS 対応ドライブが挿入されています。ノードごとにエラーが生成され、影響を受けるすべてのドライブが表示されます。

+
この問題を解決するには、該当するドライブを取り外すか交換してください。

* * FipsDrivesOutOfCompliance]
+
FIPS ドライブ機能を有効にしたあとに保存データの暗号化を無効にしたことが検出されました。このエラーは、 FIPS ドライブ機能が有効になっていて、 FIPS 非対応のドライブまたはノードがストレージクラスタに配置されている場合にも生成されます。

+
この問題を解決するには、保存データの暗号化を有効にするか、 FIPS 非対応のハードウェアをストレージクラスタから取り外してください。

* * fipsSelfTestFailure*
+
FIPS サブシステムのセルフテスト中に障害が検出されました。

+
ネットアップサポートにお問い合わせください。

* * ハードウェア構成の不一致 *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 構成がノード定義と一致しません。
** このタイプのノードに対して正しくないドライブサイズが使用されています。
** サポート対象外のドライブが検出されました。原因としては、インストールされている Element のバージョンがこのドライブを認識しないことが考えられます。このノードで Element ソフトウェアを更新することを推奨します。
** ドライブファームウェアが一致しません。
** ドライブの暗号化対応がノードと一致しません。


+
ネットアップサポートにお問い合わせください。

* *idPCertificateExpiration*
+
サードパーティのアイデンティティプロバイダ（ IdP ）で使用するクラスタのサービスプロバイダの SSL 証明書の有効期限が近づいているか、または有効期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。

|===
+
この問題を解決するには、有効期限が切れる前に SSL 証明書を更新してください。でUpdateIdpConfiguration APIメソッドを使用します `refreshCertificateExpirationTime=true` 更新されたSSL証明書を指定します。

* * inconsistentBondModes *
+
VLAN デバイスのボンディングモードが見つかりません。想定されるボンディングモードと使用中のボンディングモードが表示されます。



* * inconsistentMtus *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** Bond1G mismatch ： Bond1G インターフェイス間で異なる MTU が設定されています。
** Bond10G mismatch ： Bond10G インターフェイス間で異なる MTU が設定されています。


+
該当するノードと関連付けられている MTU 値が表示されます。

* * inconsistentRoutingRules*
+
このインターフェイスのルーティングルールが矛盾しています。

* * inconsistentSubnetMas*
+
VLAN デバイスのネットワークマスクが、内部的に記録された VLAN のネットワークマスクと一致しません。想定されるネットワークマスクと使用中のネットワークマスクが表示されます。

* * incorrectBondPortCount *
+
ボンドポートの数が正しくありません。

* * invalidConfiguredFibreChannelNodeCount *
+
想定される 2 つの Fibre Channel ノード接続のいずれかがデグレード状態です。この障害は、 Fibre Channel ノードが 1 つしか接続されていない場合に発生します。

+
この問題を解決するには、クラスタのネットワークの接続状態とケーブル配線を確認し、障害が発生したサービスがないかを確認してください。ネットワークやサービスに問題がない場合は、ネットアップサポートに連絡して Fibre Channel ノードを交換してください。

* *irqBalanceFailed*
+
割り込みのバランス調整中に例外が発生しました。

+
ネットアップサポートにお問い合わせください。

* * kmipCertificateFault * ：
+
** ルート認証局（ CA ）証明書の有効期限が近づいています。
+
この問題を解決するには、有効期限まで 30 日以上ある新しい証明書をルート CA から取得し、 ModifyKeyServerKmip を使用して更新されたルート CA 証明書を提供します。

** クライアント証明書の有効期限が近づいています。
+
この問題を解決するには、 GetClientCertificateSigningRequest を使用して新しい CSR を作成し、新しい有効期限まで 30 日以上あることを確認して署名し、 ModifyKeyServerKmip を使用して期限切れになる KMIP クライアント証明書を新しい証明書に置き換えます。

** ルート認証局（ CA ）証明書の有効期限が切れています。
+
この問題を解決するには、有効期限まで 30 日以上ある新しい証明書をルート CA から取得し、 ModifyKeyServerKmip を使用して更新されたルート CA 証明書を提供します。

** クライアント証明書の期限が切れています。
+
この問題を解決するには、 GetClientCertificateSigningRequest を使用して新しい CSR を作成し、新しい有効期限まで 30 日以上あることを確認して署名し、 ModifyKeyServerKmip を使用して期限切れの KMIP クライアント証明書を新しい証明書に置き換えます。

** ルート認証局（ CA ）証明書のエラーです。
+
この問題を解決するには、正しい証明書が指定されていることを確認し、必要に応じてルート CA から証明書を再取得します。ModifyKeyServerKmip を使用して、正しい KMIP クライアント証明書をインストールします。

** クライアント証明書エラーです。
+
この問題を解決するには、正しい KMIP クライアント証明書がインストールされていることを確認します。クライアント証明書のルート CA が EKS にインストールされている必要があります。ModifyKeyServerKmip を使用して、正しい KMIP クライアント証明書をインストールします。



* * kmipServerFault * ：
+
** 接続に失敗しました
+
この問題を解決するには、外部キーサーバが稼働しており、ネットワーク経由でアクセスできることを確認してください。TestKeyServerKimp と TestKeyProviderKmip を使用して、接続をテストします。

** 認証に失敗しました
+
この問題を解決するには、正しいルート CA および KMIP クライアント証明書が使用されていることと、秘密鍵と KMIP クライアント証明書が一致することを確認します。

** サーバエラーです
+
この問題を解決するには、エラーの詳細を確認します。エラーによっては、外部キーサーバでのトラブルシューティングが必要になる場合があります。



* * memyEccThreshold *
+
修正可能な ECC エラーまたは修正不可能な ECC エラーが多数検出されました。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===


| イベント | 重大度 | 説明 


 a| 
1 つの DIMM cErrorCount が cDimmCorrectableErrWarnThreshold に到達しました。
 a| 
警告
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM Slot>



 a| 
DIMM の cErrorFaultTimer が期限切れになるまで、 1 つの DIMM cErrorCount は cDimmCorrectableErrWarnThreshold よりも高くなります。
 a| 
エラー
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM>



 a| 
メモリコントローラが cMemCtlrCorrectableErrWarnThreshold より上の cErrorCount を報告し、 cMemCtlrCorrectableErrWarnDuration を指定します。
 a| 
警告
 a| 
修正可能な ECC メモリエラーがメモリコントローラのしきい値を超えています： <Processor><Memory Controller>



 a| 
メモリコントローラでは、メモリコントローラの cErrorFaultTimer の期限が切れるまで、メモリコントローラから cMemCtlrCorrectableErrWarnThreshold が報告されます。
 a| 
エラー
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM>



 a| 
1 つの DIMM がゼロより大きい uErrorCount を報告していますが、 cDimmUncorrectableErrFaultThreshold よりも小さくなっています。
 a| 
警告
 a| 
DIMM で修正不可能な ECC メモリエラーが検出されました： <Processor><DIMM Slot>



 a| 
1 つの DIMM で少なくとも cDimmUncorrectableErrFaultThreshold の uErrorCount が報告されます。
 a| 
エラー
 a| 
DIMM で修正不可能な ECC メモリエラーが検出されました： <Processor><DIMM Slot>



 a| 
メモリコントローラがゼロより大きい uErrorCount を報告していますが、 cMemCtlrUncorrectableErrFaultThreshold よりも小さくなっています。
 a| 
警告
 a| 
メモリコントローラで修正不可能な ECC メモリエラーが検出されました： <Processor><Memory Controller>



 a| 
メモリコントローラが少なくとも cMemCtlrUncorrectableErrFaultThreshold の uErrorCount を報告しています。
 a| 
エラー
 a| 
メモリコントローラで修正不可能な ECC メモリエラーが検出されました： <Processor><Memory Controller>

|===
+
この問題を解決するには、ネットアップサポートにお問い合わせください。

* * memoryUsageThreshold *
+
メモリ使用量が正常値を上回っています。この問題では、緊急性に基づいて次の重大度が使用されます。

+

NOTE: エラーの種類の詳細については、エラーの「 * 詳細 * 」の見出しを参照してください。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
システムメモリが不足しています。



 a| 
エラー
 a| 
システムメモリが非常に少なくなっています。



 a| 
重要
 a| 
システムメモリが完全に消費されています。

|===
+
この問題を解決するには、ネットアップサポートにお問い合わせください。

* * メタデータの ClusterFull *
+
単一ノードの損失をサポートするのに十分なメタデータストレージの空き容量がありません。クラスタフルのレベルの詳細については、 GetClusterFullThreshold API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。

+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。データをパージまたは削除するか、ノードを追加します。


+
この問題を解決するには、ボリュームをパージまたは削除するか、ストレージクラスタに別のストレージノードを追加してください。

* * mtuCheckFailure*
+
ネットワークデバイスに適切な MTU サイズが設定されていません。

+
この問題を解決するには、すべてのネットワークインターフェイスとスイッチポートでジャンボフレームが設定されている（ MTU が最大 9 、 000 バイト）ことを確認してください。

* * networkConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 想定されるインターフェイスが存在しません。
** インターフェイスが重複しています。
** 設定されたインターフェイスが停止しています。
** ネットワークの再起動が必要です。


+
ネットアップサポートにお問い合わせください。

* * 利用不可 VirtualNetworkIPAddresses*
+
IP アドレスのブロックに使用可能な仮想ネットワークアドレスがありません。

+
** virtualNetworkID #タグ（\###）には、使用可能なストレージIPアドレスがありません。クラスタにノードを追加することはできません。


+
この問題を解決するには、仮想ネットワークアドレスのブロックに IP アドレスを追加してください。

* * nodeHardwareFault （ネットワークインターフェイス <name> が停止しているか、ケーブルが接続されていません） *
+
ネットワークインターフェイスが停止しているか、ケーブルが取り外されています。

+
この問題を解決するには、ノードのネットワーク接続を確認してください。

* * nodeHardwareFault （ドライブ暗号化対応状態がスロット <node slot><drive slot> のドライブのノードの暗号化対応状態と一致しません） *
+
ドライブが、搭載されているストレージノードと暗号化機能が一致しません。

* * nodeHardwareFault （このノードタイプのスロット >< ドライブスロット > にあるドライブの < ドライブタイプ > ドライブサイズ < 実際のサイズ > が正しくありません。 < ドライブスロット > このノードタイプが想定される < 想定サイズ > ） *
+
ストレージノードに、このノードに対してサイズが正しくないドライブが含まれています。

* * nodeHardwareFault （サポートされていないドライブがスロット <node slot><drive slot> で検出されました。ドライブの統計情報と健全性情報が使用できません） *
+
ストレージノードに含まれているドライブはサポートされません。

* * nodeHardwareFault （スロット < ノードスロット >< ドライブスロット > のドライブでファームウェアバージョン < 想定バージョン > を使用している必要がありますが、サポートされていないバージョン < 実際のバージョン > を使用しています） *
+
ストレージノードに、サポート対象外のファームウェアバージョンを実行しているドライブが含まれています。

* * nodeMaintenanceMode*
+
ノードがメンテナンスモードになりました。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
ノードがまだメンテナンスモードになっていることを示します。



 a| 
エラー
 a| 
メンテナンスモードを無効にできなかったことを示します。通常は、スタンバイが失敗したかアクティブなスタンバイが原因です。

|===
+
この問題を解決するには、メンテナンスが完了したらメンテナンスモードを無効にしてください。エラーレベルの問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * nodeOffline *
+
Element ソフトウェアが指定されたノードと通信できません。ネットワーク接続を確認してください。

* * notUsingLACpBondMode *
+
LACP ボンディングモードが設定されていません。

+
この問題を解決するには、ストレージノードの導入時に LACP ボンディングを使用してください。 LACP を有効にして適切に設定していないと、クライアントでパフォーマンスの問題が発生する可能性があります。

* * ntpServerUnreachable*
+
ストレージクラスタが指定された NTP サーバと通信できません。

+
この問題を解決するには、 NTP サーバ、ネットワーク、およびファイアウォールの設定を確認してください。

* * ntpTimeNotInSync *
+
ストレージクラスタと指定された NTP サーバで時刻に大きな差があります。ストレージクラスタはこの時間差を自動的に修正できません。

+
この問題を解決するには、インストール時のデフォルトではなく、使用するネットワーク内の NTP サーバを使用してください。内部の NTP サーバを使用しても問題が維持される場合は、ネットアップサポートにお問い合わせください。

* * nvramDeviceStatus *
+
NVRAM デバイスでエラーが発生しているか、障害が発生しているか、障害が発生しています。この問題には次の重大度があります。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
ハードウェアによって警告が検出されました。この状態は、温度警告などの一時的なものです。

** nvmetimeError
** nvmetimeStatus
** energySourceLifetimeStatus
** energySourceTemperatureStatus
** warningThresholdExceeded




 a| 
エラー
 a| 
ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。警告レベルのエラーに加えて返されるエラー：

** NVRAM デバイスマウントポイントが存在しません。
** NVRAM デバイスパーティションが存在しません。
** NVRAM デバイスパーティションは存在しますが、マウントされていません。




 a| 
重要
 a| 
ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。

** 永続性ホスト
** armStatusSaveNArmed
** csaveStatusError


|===
+
ノード内の障害が発生したハードウェアを交換します。それでも問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * powerSupplyError *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 電源装置がありません。
** 電源装置で障害が発生しました。
** 電源装置の入力が見つからないか、範囲外です。


+
この問題を解決するには、冗長電源がすべてのノードに供給されていることを確認してください。ネットアップサポートにお問い合わせください。

* * provisionedSpaceTooFull*
+
クラスタのプロビジョニング済み容量がいっぱいです。

+
この問題を解決するには、プロビジョニング済みスペースを追加するか、またはボリュームを削除およびパージしてください。

* * remoteRepAsyncDelayExceeded *
+
レプリケーションに設定されている非同期遅延を超えました。クラスタ間のネットワーク接続を確認してください。

* * remoteRepClusterFull *
+
ターゲットストレージクラスタがいっぱいのため、ボリュームがリモートレプリケーションを停止しました。

+
この問題を解決するには、ターゲットストレージクラスタのスペースを解放してください。

* * remoteRepSnapshotClusterFull *
+
ターゲットストレージクラスタがいっぱいのため、ボリュームが Snapshot のリモートレプリケーションを停止しました。

+
この問題を解決するには、ターゲットストレージクラスタのスペースを解放してください。

* * remoteRepSnapshotsExceededLimit *
+
ターゲットストレージクラスタのボリュームが Snapshot の上限を超えたため、ボリュームが Snapshot のリモートレプリケーションを停止しました。

+
この問題を解決するには、ターゲットストレージクラスタの Snapshot の制限を引き上げます。

* * scheduleActionError *
+
スケジュールされたアクティビティの 1 つ以上を実行しましたが、失敗しました。

+
スケジュールされたアクティビティが再び実行されて成功するか、スケジュールされたアクティビティが削除されるか、またはアクティビティが一時停止されて再開されると、障害はクリアされます。

* * sensorReadingFailed*
+
センサーがベースボード管理コントローラ（BMC）と通信できませんでした。

+
ネットアップサポートにお問い合わせください。

* * serviceNotRunning *
+
必要なサービスが実行されていません。

+
ネットアップサポートにお問い合わせください。

* * siceServiceTooFull*
+
スライスサービスに割り当てられたプロビジョニング済み容量が少なすぎます。

+
この問題を解決するには、プロビジョニング済み容量を追加してください。

* * sliceServiceUnhealthy * が表示されます
+
スライスサービスが正常な状態でないことが検出され、サービスが自動的に停止されました。

+
** 重大度 = 警告：対処は行われません。この警告期間は 6 分後に終了します。
** 重大度 = エラー：データの運用停止処理が自動的に実行され、他の正常なドライブにデータが再レプリケートされます。


+
ネットワーク接続の問題とハードウェアエラーを確認します。特定のハードウェアコンポーネントで障害が発生した場合は、それ以外の障害が発生します。スライスサービスにアクセスできるかサービスが運用停止されると、障害は解消されます。

* * sshEnabled *
+
ストレージクラスタ内の 1 つ以上のノードで SSH サービスが有効になっています。

+
この問題を解決するには、該当するノードの SSH サービスを無効にするか、ネットアップサポートにお問い合わせください。

* * sslCertificateExpiration*
+
このノードに関連付けられている SSL 証明書の有効期限が近づいているか、期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。

|===
+
この問題を解決するには、 SSL 証明書を更新してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * strandedCapacity *
+
1 つのノードがストレージクラスタの容量の半分を超えています。

+
データの冗長性を維持するために、最大のノードの容量がシステムによって削減され、ブロック容量の一部が孤立（使用されない）状態になります。

+
この問題を解決するには、既存のストレージノードにドライブを追加するか、クラスタにストレージノードを追加してください。

* * tempSensor *
+
温度センサーが正常よりも高い温度を報告しています。この問題は、 powerSupplyError または fanSensor とともに発生する可能性があります。

+
ストレージクラスタの近くに通気を妨げる障害物がないかどうかを確認してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * アップグレード *
+
アップグレードが 24 時間以上実行中です。

+
この問題を解決するには、アップグレードを再開するか、ネットアップサポートにお問い合わせください。

* * 無対応サービス *
+
サービスが応答しなくなりました。

+
ネットアップサポートにお問い合わせください。

* * virtualNetworkConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** インターフェイスが存在しません。
** インターフェイス上のネームスペースが正しくありません。
** ネットマスクが正しくありません。
** IP アドレスが正しくありません。
** インターフェイスが稼働していません。
** ノード上に不要なインターフェイスがあります。


+
ネットアップサポートにお問い合わせください。

* * volumesDegraded *
+
セカンダリボリュームのレプリケートと同期が終了していません。このメッセージは、同期が完了するとクリアされます。

* * volumesOffline *
+
ストレージクラスタ内の 1 つ以上のボリュームがオフラインです。「 * volumeDegraded 」 * エラーも発生します。

+
ネットアップサポートにお問い合わせください。


