---
sidebar: sidebar 
permalink: vcp_task_reports_overview.html 
summary: NetApp Element Plug-in for vCenter Server のレポートページを使用して、クラスタのコンポーネントとパフォーマンスに関する情報を表示します。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report 
---
= 概要ページでクラスタ全体の健全性を監視します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element Plug-in for vCenter Server の NetApp Element Management 拡張ポイントから、レポートタブの概要ページで、選択したクラスタの全体的な容量、効率、パフォーマンスなどのクラスタ情報を確認できます。

.手順
. vCenter Plug-in で、 * NetApp Element Management* を選択します。
. [*Reporting*] を選択します。
. 概要ページでデータを監視します。




== レポート概要ページのデータ

レポート概要ページには、次のデータが表示されます。

* * クラスタ容量 * ：ブロックストレージ、メタデータ、プロビジョニングスペースの残りの容量。しきい値の情報を確認するには、進捗状況バーの上にポインタを移動します。
* * クラスタ情報 * ：クラスタ名、クラスタで実行されている NetApp Element ソフトウェアのバージョン、 MVIP アドレスと SVIP アドレス、クラスタのノード、 4k IOPS 、ボリューム、セッションの数など、クラスタに固有の情報。
+
** * Cluster Name * ：クラスタの名前。
** * Storage IP （ SVIP ） * ：ストレージ仮想 IP アドレス（ SVIP ）。
** * Management IP （ MVIP ） * ：管理仮想 IP アドレス（ MVIP ）。
** * SVIP VLAN Tag * ：マスター SVIP アドレスの VLAN 識別子。
** *MVIP VLAN Tag * ：マスター MVIP アドレスの VLAN 識別子。
** * Node Count * ：クラスタ内のアクティブノードの数。
** * クラスタの 4K IOPS * ：クラスタで 1 秒間に読み取り / 書き込みできる 4096 （ 4K ）ブロックの数。
** * Element OS Version * ：クラスタで実行されている NetApp Element ソフトウェアのバージョン。
** * Volume Count * ：クラスタ上の仮想ボリュームを除くボリュームの総数。
** * Virtual Volume Count * ：クラスタの仮想ボリュームの総数。
** * iSCSI Sessions * ：クラスタに接続されている iSCSI セッション。
** * Fibre Channel Sessions * ：クラスタに接続されている Fibre Channel セッション。


* * クラスタ効率 * ：シンプロビジョニング、重複排除、および圧縮を考慮した、システム全体の容量。クラスタでの効率化は、シンプロビジョニング、重複排除、および圧縮を使用しない従来のストレージデバイスにおける容量使用率と比較して計算されます。
* * 保護ドメイン * ：クラスタの保護ドメイン監視の概要。
+

NOTE: 保護ドメイン機能は 2 ノードクラスタには対応していません。

+
** * 保護ドメイン監視レベル * ：ユーザが選択した保護ドメインの耐障害性レベル。有効な値は、 Chassis または Node です。緑は、クラスタが選択した監視レベルに対応していることを示します。赤は、クラスタが選択した監視レベルに対応しておらず、対処が必要なことを示します。
** * Remaining Block Capacity * ：選択した耐障害性レベルを維持するために残っているブロック容量の割合を示します。
** * メタデータ容量 * ：データの可用性を中断せずに障害から回復するための十分なメタデータ容量があるかどうかを示します。Normal （緑）は、選択した監視レベルを維持するための十分なメタデータがクラスタにあることを示します。フル（赤）は、クラスタが選択した監視レベルに対応しておらず、対処が必要なことを示します。


* * プロビジョニングされた IOPS * ：クラスタ上のボリュームの IOPS について、オーバープロビジョニングの状況の概要。プロビジョニングされる IOPS の計算は、クラスタ上のすべてのボリュームの最小 IOPS 、最大 IOPS 、バースト IOPS の合計を、クラスタの最大 IOPS で割った値になります。
+

NOTE: たとえば、クラスタに 4 つのボリュームがあり、それぞれ最小 IOPS が 500 、最大 IOPS が 15 、 000 、バースト IOPS が 15 、 000 の場合、最小 IOPS の合計数は 2 、 000 、最大 IOPS の合計が 6 、 000 、バースト IOPS の合計が 6 、 000 になります。クラスタの定格の最大 IOPS が 50 、 000 の場合、計算は次のようになります。 * 最小 IOPS * ： 2000/50000 = 0.04x * 最大 IOPS * ： 60000/50000 = 1.20x * Burst IOPS * ： 60000/50000 = 1.20x 1.00x 1.00x は、プロビジョニングされた IOPS がクラスタの IOPS と同じとなるベースラインです。

* * クラスタヘルス * ：クラスタのハードウェア、容量、およびセキュリティコンポーネント。色分けは次のように表示されます。
+
** * 緑 *: 健康
** * 黄 * ：重大
** * 赤 * ：エラー


* * クラスタ入出力 * ：クラスタで現在実行されている I/O 。値は、前回の I/O 測定値と現在の I/O 測定値から計算されます。グラフに表示される測定値を次に示します。
+
** * Total * ：システムで発生している読み取りと書き込みの IOPS の合計。
** * Read * ：発生している読み取り IOPS 。
** * Write * ：書き込み IOPS 。


* * クラスタスループット * ：クラスタ上の読み取り、書き込み、および合計の帯域幅アクティビティ。
+
** * 合計 * ：クラスタ内の読み取りと書き込みの両方のアクティビティに使用されている合計 MBps 。
** * Read * ：クラスタの読み取りアクティビティ（ MB/ 秒）。
** * Write * ：クラスタの書き込みアクティビティを MBps で示します。


* * パフォーマンス利用率 * ：消費されているクラスタ IOPS の割合。たとえば、 25 万 IOPS のクラスタが 10 万 IOPS で実行されている場合、消費率は 40% です。


[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

