---
sidebar: sidebar 
permalink: vcp_task_datastores_manage.html 
summary: プラグインを使用して、 Element ボリュームに作成された管理用データストアを追加できます。 
keywords: netapp, datastore, vcp, vcenter, element 
---
= データストアを管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element Plug-in for VMware vCenter Serverでは、Elementボリュームに基づくデータストアを管理できます。データストアを作成、拡張、クローニング、共有、削除できます。また、 VAAI UNMAP 機能を使用して、シンプロビジョニングされた VMFS データストアから解放されたブロックスペースをクラスタで再生することもできます。

.必要なもの
* データストアを作成および管理するには、最初に少なくとも 1 つのユーザアカウントを作成する必要があります。
* データストアでQoSSIOCサービスを使用するには、まずプラグイン拡張ポイントのQoSSIOC設定ページで設定を行う必要があります。
+
** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenterプラグイン5.0以降を使用して設定を行います"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 4.10以前を使用して設定を行います"]


* データストアの作成には選択した ESXi ホストでサポートされる最も高い VMFS バージョンが使用されるため、 VMFS の互換性に関する問題を防ぐために、実行する vSphere および ESXi のバージョンをすべてのクラスタメンバーで統一する必要があります。


.オプション（ Options ）
*  a datastore
*  the datastore list
*  a datastore
*  a datastore
*  a datastore
*  VAAI UNMAP
*  a datastore



TIP: vSphere のタスク監視を使用して、データストア処理の進捗状況を監視します。



== データストアを作成

データストアはプラグインの拡張機能を使用して作成できます。

.必要なもの
* vCenter Server にホストが少なくとも 1 つ接続されている必要があります。
* クラスタが少なくとも 1 つ追加されて実行されている必要があります。
+

NOTE: vCenter リンクモードを使用している場合は、クラスタが追加されている vCenter Server が正しいことを確認してください。

* 少なくとも 1 つのユーザアカウントを作成する必要があります。
* データストアでQoSSIOCサービスを使用するには、プラグイン拡張ポイントからQoSSIOCの設定ページで最初に設定を行う必要があります。
+
** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 5.0以降を使用して設定を行います"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 4.10以前を使用して設定を行います"]




.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. データストアページで、 * データストアの作成 * を選択します。
. データストアの名前を入力します。
+

TIP: データセンター内のデータストアごとに一意の名前を使用します。複数のクラスタや vCenter Server を使用する環境では、わかりやすい名前のベストプラクティスを使用してください。

. 「 * 次へ * 」を選択します。
. データストアに必要なホストを 1 つ以上選択します。
+

NOTE: 新しいデータストアを作成するには、ホストが少なくとも 1 つ接続されている必要があります。ホストに複数のイニシエータがある場合は、 1 つのイニシエータまたはホストを選択してすべてのイニシエータを選択します。vCenter リンクモードを使用している場合は、クラスタが割り当てられている vCenter Server で使用可能なホストのみを選択できます。

. 「 * 次へ * 」を選択します。
. Configure Volume （ボリュームの設定） * ペインで、既存のボリュームを選択して次の手順に進むか、新しいデータストア用の新しいボリュームを作成します。
+

NOTE: 既存のボリュームを選択して新しいデータストアを作成すると、既存のデータは失われます。既存の VMFS ボリュームについては、 VMware のドキュメントを参照してください https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFS データストアのコピーをマウントしています"^] および https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["重複する VMFS データストアの管理"^]。

+
.. データストアの基盤となるボリュームの名前を入力します。
.. アカウントリストからユーザアカウントを選択します。
.. 作成するボリュームの合計サイズを入力します。
+

NOTE: デフォルトで選択されているボリュームサイズの単位は GB です。ボリュームは、 GB または GiB 単位のサイズを使用して作成できます。 1GB = 1 000 000 000 バイト 1GiB = 1 073 741 824 バイト

+
デフォルトでは、すべての新しいボリュームについて、 512 バイトエミュレーションが ON に設定されます。

.. [* Quality of Service* （サービス品質 * ） ] 領域で、次のいずれかを実行します。
+
... * Policy * で、既存の QoS ポリシーを選択します。
... カスタム設定 * で、 IOPS の最小値、最大値、バースト値をカスタマイズするか、デフォルトの QoS 値を使用します。
+

TIP: QoS ポリシーは、データベースサーバ、アプリケーションサーバ、インフラサーバなど、ほとんどリブートされずにストレージへの常時アクセスが必要となるサービス環境に最適です。カスタム QoSSIOC 自動化は、仮想デスクトップや専用キオスクタイプの VM など、毎日または数回、リブート、電源オン、電源オフが可能な軽量の VM に最適です。QoSSIOC 自動化ポリシーと QoS ポリシーを一緒に使用しないでください。

+

TIP: 最大 IOPS またはバースト IOPS の値が 20 、 000 IOPS を超える場合、単一のボリュームでこのレベルの IOPS を実現するには、キュー深度を深くするか、複数のセッションが必要になる場合があります。





. 「 * 次へ * 」を選択します。
. 次のいずれかを選択して、ホストアクセスの認証タイプを設定します。
+
** * ボリュームアクセスグループを使用 * ：ボリュームを認識できるイニシエータを明示的に制限する場合に選択します。
** * Use CHAP * ：イニシエータを制限しないセキュアなシークレットベースのアクセスの場合に選択します。


. 「 * 次へ * 」を選択します。
. ボリュームアクセスグループを使用するを選択した場合は、選択したホストのボリュームアクセスグループを設定します。
+
「選択したイニシエータで必要」にリストされているボリュームアクセスグループは、前の手順で選択した 1 つ以上のホストイニシエータにすでに関連付けられています

+
.. 追加のボリュームアクセスグループを選択するか、または新しいグループを作成して、使用可能なイニシエータに関連付けます。
+
*** * available * ：クラスタ内のその他のボリュームアクセスグループオプション。
*** * 新しいアクセスグループの作成 *: 新しいアクセスグループの名前を入力し、 *Add* を選択します。


.. 「 * 次へ * 」を選択します。
.. [Configure Hosts' Access * （ホストのアクセスの設定） ] ペインで、前のペインで選択したボリュームアクセスグループに、使用可能なホストイニシエータ（ IQN または WWPN ）を関連付けます。ボリュームアクセスグループがすでに関連付けられているホストイニシエータの場合、このフィールドは読み取り専用です。ボリュームアクセスグループに関連付けられていない場合は、イニシエータの横にあるリストから該当するオプションを選択します。
.. 「 * 次へ * 」を選択します。


. QoSSIOC 自動化を有効にする場合は、 QoS と SIOC を有効にする * をオンにしてから、 QoSSIOC を設定します。
+
--

TIP: QoS ポリシーを使用する場合は、 QoSSIOC を有効にしないでください。QoSSIOC は上書きされ、ボリュームの QoS 設定の QoS 値が調整されます。

QoSSIOCサービスを使用できない場合は、最初にQoSSIOCを設定する必要があります。

** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenterプラグイン5.0以降を使用して設定を行います"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 4.10以前を使用して設定を行います"]


--
+
.. 「 QoS と SIOC を有効にする」を選択します。
.. * バースト係数 * を設定します。
+

NOTE: バースト係数は、 VMDK の IOPS 制限（ SIOC ）設定を乗算する係数です。デフォルト値を変更する場合は、すべての VMDK について、 IOPS 制限にこの係数を掛けても Element ボリュームの最大バースト制限を超えない値を指定してください。

.. （任意） [*Override default QoS] を選択し、設定を行います。
+

NOTE: データストアに対して「デフォルトの QoS 設定を上書き」が無効になっている場合は、各 VM のデフォルトの SIOC 設定に基づいて、共有 IOPS と制限 IOPS の値が自動的に設定されます。

+

TIP: SIOC シェア制限をカスタマイズするときは、 SIOC IOPS 制限も必ずカスタマイズしてください。

+

TIP: デフォルトでは、 SIOC のディスク共有の最大数は「無制限」に設定されています。VDI などの大規模な VM 環境では、クラスタの最大 IOPS がオーバーコミットされる可能性があります。QoSSIOC を有効にするときは、常にデフォルト QoS を上書きするオプションをオンにして、 IOPS 制限オプションを適切な値に設定してください。



. 「 * 次へ * 」を選択します。
. 選択を確定し、 * 完了 * をクリックします。
. タスクの進捗状況を表示するには、 vSphere のタスク監視を使用します。データストアがリストに表示されない場合は、ビューを更新します。




== データストアリストを表示します

Plug-in拡張ポイントからは、Datastoresページ上の使用可能なデータストアを表示できます。

. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. データストアのリストを確認します。
+

NOTE: 複数のボリュームにまたがるデータストア（混在データストア）はリストに表示されません。データストアビューには、選択した NetApp Element クラスタの ESXi ホストで使用可能なデータストアのみが表示されます。

. 次の点について確認
+
** * Name * ：データストアに割り当てられた名前。
** * ホスト名 * ：関連付けられている各ホストデバイスのアドレス。
** * ステータス * ：「 accessible 」または「 Inaccessible 」の値は、データストアが現在 vSphere に接続されているかどうかを示します。
** * タイプ * ： VMware ファイルシステムのデータストアタイプ。
** * ボリューム名 * ：関連付けられたボリュームに割り当てられている名前。
** * Volume NAA * ： NAA IEEE Registered Extended フォーマットで関連付けられたボリュームのグローバル一意 SCSI デバイス ID 。
** * 合計容量（ GB ） * ：データストアのフォーマット後の総容量。
** * 空き容量（ GB ） * ：データストアで使用可能なスペース。
** * QoSSIOC 自動化 * ： QoSSIOC 自動化が有効になっているかどうか。有効な値は次のとおり
+
*** [Enabled （有効） ] ： QoSSIOC は有効です。
*** 「 Disabled 」： QoSSIOC は無効です。
*** 「最大 QoS を超えました」：ボリュームの最大 QoS が指定された制限値を超えました。








== データストアを拡張する

プラグインの拡張ポイントを使用して、データストアを拡張してボリュームのサイズを大きくすることができます。データストアを拡張すると、そのデータストアに関連する VMFS ボリュームも拡張されます。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. Datastores ページで、拡張するデータストアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * 延長 * を選択します。
. New Datastore Size （新しいデータストアのサイズ）フィールドに、新しいデータストアに必要なサイズを入力し、 GB または GiB を選択します。
+

NOTE: データストアの拡張では、ボリューム全体のサイズが消費されます。新しいデータストアのサイズは、選択したクラスタで利用できるプロビジョニングされていないスペースよりも大きくすることはできません。また、クラスタで許容される最大ボリュームサイズ以下でなければなりません。

. 「 * OK 」を選択します。
. ページをリフレッシュしてください




== データストアのクローニング

プラグインを使用してデータストアをクローニングできます。これには、目的の ESXi サーバまたはクラスタに新しいデータストアをマウントする作業が含まれます。作成したデータストアのクローンに名前を付け、 QoSSIOC 、ボリューム、ホスト、および認証タイプを設定できます。

ソースデータストアに仮想マシンが存在する場合は、クローンデータストア上の仮想マシンが新しい名前でインベントリに格納されます。

クローンデータストアのボリュームサイズは、ソースデータストアを構成するボリュームのサイズと同じになります。デフォルトでは、すべての新しいボリュームについて、 512 バイトエミュレーションが ON に設定されます。

.必要なもの
* vCenter Server にホストが少なくとも 1 つ接続されている必要があります。
* クラスタが少なくとも 1 つ追加されて実行されている必要があります。
+

NOTE: vCenter リンクモードを使用している場合は、クラスタが追加されている vCenter Server が正しいことを確認してください。

* ソースボリュームのサイズと同じかそれ以上のプロビジョニングされていない利用可能なスペースが必要です。
* 少なくとも 1 つのユーザアカウントを作成する必要があります。


.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. [* Datastores * （データストア * ） ] ページで、クローニングするデータストアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * Clone * を選択します。
+

NOTE: クローニングするデータストアにそのデータストアにないディスクが接続された仮想マシンが含まれている場合、クローンの作成後、その仮想マシンのコピーは仮想マシンインベントリに追加されません。

. データストア名を入力します。
+

TIP: データセンター内のデータストアごとに一意の名前を使用します。複数のクラスタや vCenter Server を使用する環境では、わかりやすい名前のベストプラクティスを使用してください。

. 「 * 次へ * 」を選択します。
. データストアに必要なホストを 1 つ以上選択します。
+

NOTE: 新しいデータストアを作成するには、ホストが少なくとも 1 つ接続されている必要があります。ホストに複数のイニシエータがある場合は、 1 つのイニシエータまたはホストを選択してすべてのイニシエータを選択します。vCenter リンクモードを使用している場合は、クラスタが割り当てられている vCenter Server で使用可能なホストのみを選択できます。

. 「 * 次へ * 」を選択します。
. [Configure Volume] ペインで、次の操作を行います。
+
.. クローンデータストアを構成する新しい NetApp Element の名前を入力します。
.. アカウントリストからユーザアカウントを選択します。
+

NOTE: ボリュームを作成するには、既存のユーザアカウントが少なくとも 1 つ必要です。

.. [* Quality of Service* （サービス品質 * ） ] 領域で、次のいずれかを実行します。
+
*** 「 * Policy 」で、既存の QoS ポリシーがある場合は選択します。
*** カスタム設定 * で、 IOPS の最小値、最大値、バースト値をカスタマイズするか、デフォルトの QoS 値を使用します。
+

TIP: QoS ポリシーは、データベースサーバ、アプリケーションサーバ、インフラサーバなど、ほとんどリブートされずにストレージへの常時アクセスが必要となるサービス環境に最適です。カスタム QoSSIOC 自動化は、仮想デスクトップや専用キオスクタイプの VM など、毎日または数回、リブート、電源オン、電源オフが可能な軽量の VM に最適です。QoSSIOC 自動化ポリシーと QoS ポリシーを一緒に使用しないでください。

+

TIP: 最大 IOPS またはバースト IOPS の値が 20 、 000 IOPS を超える場合、単一のボリュームでこのレベルの IOPS を実現するには、キュー深度を深くするか、複数のセッションが必要になる場合があります。





. 「 * 次へ * 」を選択します。
. 次のいずれかのオプションを選択して、ホストアクセスの認証タイプを設定します。
+
** * ボリュームアクセスグループを使用 * ：ボリュームを認識できるイニシエータを明示的に制限する場合に選択します。
** * Use CHAP * ：イニシエータを制限しないセキュアなシークレットベースのアクセスの場合に選択します。


. 「 * 次へ * 」を選択します。
. ボリュームアクセスグループを使用するを選択した場合は、選択したホストのボリュームアクセスグループを設定します。
+
「選択したイニシエータで必要」にリストされているボリュームアクセスグループは、前の手順で選択した 1 つ以上のホストイニシエータにすでに関連付けられています。

+
.. 追加のボリュームアクセスグループを選択するか、または新しいグループを作成して、使用可能なイニシエータに関連付けます。
+
*** * available * ：クラスタ内のその他のボリュームアクセスグループオプション。
*** * 新しいアクセスグループの作成 *: 新しいアクセスグループの名前を入力し、 *Add* をクリックします。


.. 「 * 次へ * 」を選択します。
.. [Configure Hosts' Access * （ホストのアクセスの設定） ] ペインで、前のペインで選択したボリュームアクセスグループに、使用可能なホストイニシエータ（ IQN または WWPN ）を関連付けます。
+
ボリュームアクセスグループがすでに関連付けられているホストイニシエータの場合、このフィールドは読み取り専用です。ボリュームアクセスグループに関連付けられていない場合は、イニシエータの横にあるドロップダウンリストから該当するオプションを選択します。

.. 「 * 次へ * 」を選択します。


. QoSSIOC 自動化を有効にする場合は、「 QoS と SIOC を有効にする」チェックボックスをオンにしてから、 QoSSIOC を設定します。
+
--

IMPORTANT: QoS ポリシーを使用する場合は、 QoSSIOC を有効にしないでください。QoSSIOC は上書きされ、ボリュームの QoS 設定の QoS 値が調整されます。

QoSSIOCサービスを使用できない場合は、プラグイン拡張ポイントからQoSSIOCの設定ページで最初に設定する必要があります。

** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenterプラグイン5.0以降を使用して設定を行います"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 4.10以前を使用して設定を行います"]


--
+
.. 「 QoS と SIOC を有効にする」を選択します。
.. * バースト係数 * を設定します。
+

NOTE: バースト係数は、 VMDK の IOPS 制限（ SIOC ）設定を乗算する係数です。デフォルト値を変更する場合は、すべての VMDK について、 IOPS 制限にこの係数を掛けても NetApp Element ボリュームの最大バースト制限を超えない値を指定してください。

.. * オプション * ： [* Override default QoS] を選択し、設定を行います。
+
データストアに対して「デフォルトの QoS 設定を上書き」が無効になっている場合は、各 VM のデフォルトの SIOC 設定に基づいて、共有 IOPS と制限 IOPS の値が自動的に設定されます。

+

TIP: SIOC シェア制限をカスタマイズするときは、 SIOC IOPS 制限も必ずカスタマイズしてください。

+

TIP: デフォルトでは、 SIOC のディスク共有の最大数は「無制限」に設定されています。VDI などの大規模な VM 環境では、クラスタの最大 IOPS がオーバーコミットされる可能性があります。QoSSIOC を有効にするときは、常にデフォルト QoS を上書きするオプションをオンにして、 IOPS 制限オプションを適切な値に設定してください。



. 「 * 次へ * 」を選択します。
. 選択を確定し、 * 完了 * を選択します。
. ページをリフレッシュしてください




== データストアを共有する

プラグインの拡張ポイントを使用して、データストアを1つ以上のホストと共有できます。

データストアは、同じデータセンター内のホスト間でのみ共有できます。

.必要なもの
* クラスタが少なくとも 1 つ追加されて実行されている必要があります。
+

NOTE: vCenter リンクモードを使用している場合は、クラスタが追加されている vCenter Server が正しいことを確認してください。

* 選択したデータセンターに複数のホストがある。


.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. [* Datastores] ページで、共有するデータストアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、「 * 共有」を選択します。
. 次のいずれかのオプションを選択して、ホストアクセスの認証タイプを設定します。
+
** * ボリュームアクセスグループを使用 * ：このオプションは、どのイニシエータがボリュームを認識できるかを明示的に制限する場合に選択します。
** * Use CHAP * ：イニシエータを制限せずにシークレットベースのセキュアなアクセスを行う場合に選択します。


. 「 * 次へ * 」を選択します。
. データストアに必要なホストを 1 つ以上選択します。
+

NOTE: 新しいデータストアを作成するには、ホストが少なくとも 1 つ接続されている必要があります。ホストに複数のイニシエータがある場合は、いずれかのイニシエータを選択するか、またはホストを選択してすべてのイニシエータvCenter リンクモードを使用している場合は、クラスタが割り当てられている vCenter Server で使用可能なホストのみを選択できます。

. 「 * 次へ * 」を選択します。
. ボリュームアクセスグループを使用するを選択した場合は、選択したホストのボリュームアクセスグループを設定します。
+
「選択したイニシエータで必要」にリストされているボリュームアクセスグループは、前の手順で選択した 1 つ以上のホストイニシエータにすでに関連付けられています。

+
.. 追加のボリュームアクセスグループを選択するか、または新しいグループを作成して、使用可能なイニシエータに関連付けます。
+
*** * available * ：クラスタ内のその他のボリュームアクセスグループオプション。
*** * 新しいアクセスグループの作成 *: 新しいアクセスグループの名前を入力し、 *Add* をクリックします。


.. 「 * 次へ * 」を選択します。
.. [Configure Hosts' Access * （ホストのアクセスの設定） ] ペインで、前のペインで選択したボリュームアクセスグループに、使用可能なホストイニシエータ（ IQN または WWPN ）を関連付けます。
+
ボリュームアクセスグループがすでに関連付けられているホストイニシエータの場合、このフィールドは読み取り専用です。ボリュームアクセスグループに関連付けられていない場合は、イニシエータの横にあるドロップダウンリストから該当するオプションを選択します。



. 選択を確定し、 * 完了 * を選択します。
. ページをリフレッシュしてください




== VAAI UNMAP を実行します

シンプロビジョニングされた VMFS5 データストアから解放されたブロックスペースをクラスタで再生するには、 VAAI UNMAP 機能を使用します。

.必要なもの
* タスクに使用するデータストアが VMFS5 以前のものであることを確認します。VMFS6 では、 ESXi で自動的に実行されるため、 VAAI UNMAP は使用できません
* ESXi ホストのシステム設定で VAAI UNMAP が有効になっていることを確認します。
+
esxcli system settings advanced list -o /VMFS3/EnableBlockDelete ’

+
有効にするには、整数値を 1 に設定する必要があります。

* ESXi ホストのシステム設定で VAAI UNMAP が有効になっていない場合は、次のコマンドを使用して値を 1 に設定します。
+
esxcli system settings advanced set -i 1 -o /VMFS3/EnableBlockDelete 」を参照してください



.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. [* Datastores] ページで、 VAAI UNMAP を使用するデータストアのチェックボックスを選択します。
. 表示されたメニューで、 * アクション * を選択します。
. VAAI Unmap * を選択します。
. 名前または IP アドレスでホストを選択します。
. ホストのユーザ名とパスワードを入力します。
. 選択を確定し、 * OK * を選択します。




== データストアを削除する

プラグイン拡張ポイントを使用して、データストアを削除できます。この処理を実行すると、データストア上の、削除する VM に関連付けられているすべてのファイルが完全に削除されます。プラグインでは、登録済みの VM を含むデータストアは削除されません。

. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、ナビゲーションバーで使用するクラスタを選択します。

. [* Datastores * （データストア * ） ] ページで、削除するデータストアのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * 削除 * を選択します。
. （オプション）データストアに関連付けられている NetApp Element ボリュームを削除する場合は、関連するボリュームの削除 * チェックボックスを選択します。
+

NOTE: ボリュームを削除せずに残し、あとで別のデータストアに関連付けることもできます。

. 「 * はい * 」を選択します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

