---
sidebar: sidebar 
permalink: vcp_task_add_manage_nodes.html 
summary: プラグインを使用して、クラスタ構成内のノードを作成および管理できます。 
keywords: netapp, nodes, create, manage, delete, view vcp, vcenter, element 
---
= ノードを追加および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter Plug-in を使用して、を追加できます https://docs.netapp.com/us-en/hci/docs/concept_hci_nodes.html#storage-nodes["ストレージノード"] クラスタを作成する場合やストレージの追加が必要な場合。NetApp Element Management 拡張ポイントを使用して、 Element ソフトウェアを実行するストレージノードを追加できます。NetApp HCI コンピューティングノードは、 vSphere のプラグイン以外で追加および管理する必要があります。

* <<Add a node to a cluster>>
* <<View node details>>
* <<Restart a node>>
* <<Shut down a node>>
* <<Remove a node from a cluster>>




== クラスタにノードを追加します

vCenter Plug-in を使用して、クラスタにストレージノードを追加できます。

.必要なもの
* 追加するノードのセットアップ、電源投入、設定を完了しておきます。
* ソフトウェアの互換性を確保するためには、クラスタ内の各ノードのソフトウェアのメジャーバージョン番号とマイナーバージョン番号が一致している必要があります。たとえば、 Element 9.0 とバージョン 9.1 は互換性がありません。



NOTE: 追加するノードの NetApp Element ソフトウェアのメジャーバージョンまたはマイナーバージョンがクラスタで実行されているバージョンと異なる場合、クラスタマスターで実行されている NetApp Element ソフトウェアのバージョンに非同期的に更新されます。更新されたノードは、自動的にクラスタに追加されます。この非同期プロセスの間 ' ノードの状態は pendingActive になります

ノードは、初回の電源投入時に初期設定を行う必要があります。ノードは、セットアップと設定が完了すると、ノードの設定時に識別されたクラスタに自身が登録され、 NetApp Element 管理拡張ポイントの * Cluster > Nodes * ページにある保留中のノードのリストに表示されます。

既存のクラスタには、大小さまざまな容量のノードを追加できます。

手順は、 NetApp Element ソフトウェアを実行している Fibre Channel ノードまたはストレージノードを追加する場合と同じです。

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブをクリックします。
. ドロップダウンリストから「 * Pending * 」を選択して、ノードのリストを表示します。
. ノードを追加するには、次の手順を実行します。
+
.. 追加する各ノードのチェックボックスを選択します。
.. [ ノードの追加 ] をクリックします。


. 追加するノードの詳細を確認し、操作を確定します。
+
操作が完了すると、ノードがクラスタのアクティブノードのリストに表示されます。





== ノードの詳細を表示します

NetApp Element Management 拡張ポイントから、クラスタタブのノードページにクラスタ内のノードのリストを表示できます。アクティブなノードのリストを表示するには、アクティブなビューを選択する必要があります。ドロップダウン・フィルタを使用して ' Pending ' ' 'PendingActive ' および all のオプションを選択すると ' ビューを変更できます

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
. [ アクティブ（ * Active ） ] ビューを選択します。
. ストレージクラスタ内のノードの詳細を表示します。
+
ノード ID 、各ノードの名前と状態、設定されている IOPS 、ノードタイプ、各ノードのアクティブドライブの数、各ノードのネットワーク情報などの情報を確認できます。





== ノードを再起動します

NetApp Element Management 拡張ポイントを使用して、クラスタ内の 1 つ以上のアクティブノードを再起動できます。

同時に複数のノードを再起動する場合は、 I/O を停止し、すべての iSCSI セッションを切断しておきます。

クラスタを再起動するには、すべてのクラスタノードを選択して再起動します。


IMPORTANT: このメソッドは、ノードのすべてのネットワークサービスを再起動します。このため、ネットワーク接続が一時的に失われます。


NOTE: この機能は、 SolidFire エンタープライズ SDS クラスタでは使用できません。

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
+
.. アクティブ * ビューで、再起動する各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * Restart * 」を選択します。


. 操作を確定します。




== ノードをシャットダウン

NetApp Element Management 拡張ポイントを使用して、クラスタ内の 1 つ以上のアクティブノードをシャットダウンできます。クラスタをシャットダウンするには、すべてのクラスタノードを選択して同時にシャットダウンします。

同時に複数のノードを再起動する場合は、 I/O を停止し、すべての iSCSI セッションを切断しておきます。

.このタスクについて

NOTE: この機能は、 SolidFire エンタープライズ SDS クラスタでは使用できません。

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
+
.. アクティブ * ビューで、シャットダウンする各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * Shutdown * 」を選択します。


. 操作を確定します。



NOTE: ノードが何らかの理由でシャットダウン状態になって 5 分半以上が経過すると、 NetApp Element ソフトウェアはノードが再びクラスタに参加することはないと判断します。Double Helix データ保護は、レプリケートされた個々のブロックを別のノードに書き込んでデータをレプリケートするタスクを開始します。ノードがシャットダウンしていた時間によっては、ノードがオンラインに戻ったあとにドライブを再度クラスタに追加する必要があります。



== クラスタからノードを削除します

ノードのストレージが不要になったときや、ノードのメンテナンスが必要なときは、サービスを中断することなくクラスタからノードを削除できます。

ノード内のすべてのドライブをクラスタから削除しておきます。RemoveDrives プロセスが完了してすべてのデータがノードから移行されるまで、ノードを削除することはできません。

NetApp Element クラスタでの Fibre Channel 接続には、少なくとも 2 つの Fibre Channel ノードが必要です。Fibre Channel ノードが 1 つだけ接続されている場合は、クラスタに別の Fibre Channel ノードを追加するまでイベントログにアラートがトリガーされます。これは、すべての Fibre Channel ネットワークトラフィックが 1 つの Fibre Channel ノードでのみ動作を継続する場合でも同様です。

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
. 1 つ以上のノードを削除するには、次の手順を実行します。
+
.. アクティブ * ビューで、削除する各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * 削除」を選択します。


. 操作を確定します。
+
クラスタから削除したノードがすべて Pending 状態のノードのリストに表示されます。


