---
sidebar: sidebar 
permalink: vcp_task_qos_policies.html 
summary: QoS ポリシーを設定および変更して、ストレージクラスタ内のボリュームに適用することができます。 
keywords: netapp, qos policy, quality of service, qos policies, vcp, vcenter, element 
---
= ボリュームの QoS ポリシーの作成と管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
標準的なサービス品質設定を QoS ポリシーとして作成および保存して、複数のボリュームに適用することができます。QoS ポリシーを使用するには、 Element 10.0 以降のクラスタを選択する必要があります。 10.0 より前のクラスタでは QoS ポリシーを使用できません。

NetApp Element Management 拡張ポイントを使用すると、次のタスクを実行して QoSSIOC を設定および管理できます。

* <<Create a QoS policy>>
* <<Apply a QoS policy to volumes>>
* <<Change the QoS policy association of a volume>>
* <<Edit a QoS policy>>
* <<Delete a QoS policy>>




== QoS ポリシーを作成する

QoS ポリシーを作成し、同等のパフォーマンスが必要なボリュームに適用することができます。


NOTE: QoSSIOC 自動化ポリシーと QoS ポリシーを一緒に使用しないでください。QoS ポリシーを使用する場合は、 QoSSIOC を有効にしないでください。QoSSIOC は上書きされ、ボリュームの QoS 設定の QoS 値が調整されます。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* QoS Policies] サブタブをクリックします。
. [Create QoS Policy] をクリックします。
. 「 * ポリシー名 * 」を入力します。
+

TIP: わかりやすい名前のベストプラクティスを使用してください。これは、環境で複数のクラスタや vCenter Server を使用している場合に特に重要です。

. 最小 IOPS 、最大 IOPS 、バースト IOPS の値を入力します。
. [OK] をクリックします。




== ボリュームに QoS ポリシーを適用する

既存の QoS ポリシーを複数のボリュームに適用することができます。このプロセスは、ポリシーを 1 つ以上のボリュームに一括して適用する場合に使用します。

一括して適用する QoS ポリシーを用意しておきます <<Create a QoS policy,作成済み>>。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブをクリックします。
. QoS ポリシーを適用する各ボリュームのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * QoS ポリシーの適用 * を選択します。
. ダイアログボックスで、選択したボリュームに適用する QoS ポリシーをドロップダウンリストから選択します。
. [OK] をクリックします。




== ボリュームの QoS ポリシーの関連付けを変更します

QoS ポリシーのボリュームへの関連付けを解除したり、別の QoS ポリシーやカスタム QoS を選択したりできます。

変更するボリュームはです <<Apply a QoS policy to volumes,関連付けられました>> QoS ポリシーを使用する。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブをクリックします。
. 変更する QoS ポリシーが含まれているボリュームのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. ダイアログボックスの「 * Quality of Service * 」で、ボリュームに適用する新しい QoS ポリシーまたはカスタム設定を選択します。
. カスタム設定を選択した場合は、 * Min IOPS * 、 * Max IOPS * 、 * Burst IOPS * の値を変更します。
+

NOTE: デフォルトの QoS のリセット * をクリックして、デフォルトの IOPS 値に戻すこともできます。

. [OK] をクリックします。




== QoS ポリシーを編集する

既存の QoS ポリシーの名前を変更したり、ポリシーに関連付けられている値を編集したりできます。QoS ポリシーのパフォーマンス値を変更すると、そのポリシーに関連付けられているすべてのボリュームの QoS に影響します。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* QoS Policies] サブタブをクリックします。
. 編集する QoS ポリシーのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. Edit QoS Policy * ダイアログボックスで、必要に応じて次のプロパティを変更します。
+
** * Policy Name * ： QoS ポリシーのユーザ定義名。
** * Min IOPS * ：ボリュームに対して保証されている最小 IOPS 。
** * Max IOPS * ：ボリュームで許可されている最大 IOPS 。
** * Burst IOPS * ：ボリュームに対して短期間で許可されている最大 IOPS 。デフォルト値は 15 、 000 です。
+

NOTE: デフォルトの QoS のリセットをクリックして、デフォルトの IOPS 値に戻すこともできます。



. [OK] をクリックします。




== QoS ポリシーを削除する

不要になった QoS ポリシーを削除できます。QoS ポリシーを削除すると、そのポリシーに関連付けられているすべてのボリュームで、これまでにそのポリシーで定義されていた QoS 値が個々のボリュームの QoS 値として維持されます。削除された QoS ポリシーとの関連付けがすべて削除されます。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* QoS Policies] サブタブをクリックします。
. 削除する QoS ポリシーのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。


[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

