---
sidebar: sidebar 
permalink: vcp_task_create_manage_access_groups.html 
summary: プラグインを使用して、ボリュームアクセスグループを作成および管理できます。 
keywords: netapp, storage, access groups, vcp, vcenter, element 
---
= ボリュームアクセスグループを作成および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A link:https://docs.netapp.com/us-en/hci/docs/concept_hci_volume_access_groups.html["ボリュームアクセスグループ"] は、ユーザがiSCSIイニシエータまたはFCイニシエータを使用してアクセスできるボリュームの集まりです。

アクセスグループを作成するには、iSCSIイニシエータのIQNまたはFCのWWPNをボリュームのグループにマッピングします。アクセスグループに追加した各 IQN は、 CHAP 認証なしでグループ内の各ボリュームにアクセスできます。アクセスグループに追加した各WWPNは、アクセスグループ内のボリュームへのFCネットワークアクセスを可能にします。

.オプション（ Options ）
*  an access group
*  an access group
*  volumes to an access group
*  volumes from an access group
*  an access group




== アクセスグループを作成します

1 つ以上のイニシエータを含むボリュームアクセスグループを作成できます。クライアントの Fibre Channel （ WWPN ）イニシエータまたは iSCSI （ IQN ）イニシエータをボリュームアクセスグループ内のボリュームにマッピングすることで、ネットワークとボリュームの間の安全なデータ I/O 通信が実現します。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アクセスグループ * （ Access Groups * ） ] サブタブを選択します。
. [ アクセスグループの作成 *] を選択します。
. ボリュームアクセスグループの名前を入力します。
+

TIP: わかりやすい名前のベストプラクティスを使用してください。これは、環境で複数のクラスタや vCenter Server を使用している場合に特に重要です。

. [ イニシエータの選択 *] ドロップダウンリストから未割り当ての IQN または WWPN を選択し、 [ イニシエータの追加 *] をクリックします。
+

NOTE: イニシエータは、ボリュームアクセスグループの作成後に追加または削除できます。

. [OK] をクリックしてアクセスグループを作成します。




== アクセスグループを編集します

プラグイン拡張ポイントで、ボリュームアクセスグループの名前を編集したり、イニシエータの追加や削除を行ったりすることができます。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アクセスグループ * （ Access Groups * ） ] サブタブを選択します。
. 編集するボリュームアクセスグループのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. 必要に応じて次の項目を変更します。
+
.. アクセスグループの名前を変更します。
.. イニシエータを追加または削除します。
+

NOTE: イニシエータを削除するときは、ごみ箱アイコンをクリックして削除します。イニシエータを削除すると、そのイニシエータはボリュームアクセスグループ内のボリュームにアクセスできなくなります。ボリュームへの通常のアカウントアクセスは引き続き可能です。



. 「 * OK 」を選択します。




== アクセスグループにボリュームを追加する

ボリュームアクセスグループにボリュームを追加できます。各ボリュームは複数のボリュームアクセスグループに属することができます。各ボリュームが属しているグループはアクティブなボリュームビューで確認できます。

.必要なもの
* クラスタが少なくとも 1 つ追加されて実行されている必要があります。
* 少なくとも 1 つのアクセスグループが必要です。
* 少なくとも 1 つのアクティブなボリュームが必要です。


.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. * Volumes * サブタブを選択します。
. アクセスグループに追加する各ボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. ［ * アクセスグループに追加 * ］ を選択します。
. 詳細を確認し、リストからボリュームアクセスグループを選択します。
. 「 * OK 」を選択します。




== アクセスグループからボリュームを削除します

アクセスグループからボリュームを削除できます。

アクセスグループからボリュームを削除すると、グループはそのボリュームにアクセスできなくなります。


IMPORTANT: アクセスグループからボリュームを削除すると、ボリュームへのホストアクセスが中断される可能性があります。

. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. * Volumes * サブタブを選択します。
. アクセスグループから削除する各ボリュームのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. [ アクセスグループから削除 *] を選択します。
. 詳細を確認し、選択した各ボリュームへのアクセスを中止するボリュームアクセスグループを選択します。
. 「 * OK 」を選択します。




== アクセスグループを削除する

プラグイン拡張ポイントを使用して、ボリュームアクセスグループを削除できます。ボリュームアクセスグループを削除する前に、イニシエータ ID を削除したり、グループとボリュームの関連付けを解除したりする必要はありません。アクセスグループを削除すると、ボリュームへのグループアクセスが切断されます。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アクセスグループ * （ Access Groups * ） ] サブタブを選択します。
. 削除するアクセスグループのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

