---
sidebar: sidebar 
permalink: vcp_task_add_manage_drive.html 
summary: プラグインを使用して、クラスタへのドライブの追加と管理を行うことができます。 
keywords: netapp, drives, add, manage, remove, view vcp, vcenter, element 
---
= ドライブを追加および管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element 管理拡張ポイントを使用して、クラスタへのドライブの追加、既存のドライブの表示、およびドライブの削除を行うことができます。

* <<Add available drives to a cluster>>
* <<View drive details>>
* <<Remove a drive>>




== クラスタに使用可能なドライブを追加します

NetApp Element Management 拡張ポイントを使用して、クラスタにドライブを追加できます。ノードをクラスタに追加するとき、または既存のノードに新しいドライブをインストールするとき、ドライブは自動的に「 available 」として登録されます。各ドライブがクラスタに参加できるようにするには、ドライブをクラスタに追加しておく必要があります。

次の状況に該当するドライブはリストに表示されません。

* ドライブは「 Active 」、「 Removing 」、「 Erasing 」、「 Failed 」のいずれかの状態です。
* ドライブが含まれているノードは「 Pending 」状態です。


.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Drives * （ドライブ * ） ] サブタブで、ドロップダウンリストから [* Available* （使用可能 * ） ] を選択して、使用可能なドライブのリストを表示します。
. 次の手順でドライブを追加します。
+
.. 追加する各ドライブのチェックボックスを選択します。
.. [ ドライブの追加 ] をクリックします。


. 追加するドライブの詳細を確認し、操作を確定します。




== ドライブの詳細を表示します

NetApp Element Management 拡張ポイントから、クラスタタブの Drives ページにある Active ビューを使用して、クラスタ内のアクティブドライブのリストを表示できます。ドロップダウンフィルタを使用して使用可能なオプションを選択すると、ビューを変更できます。

クラスタを最初に初期化した時点では、アクティブドライブのリストは空です。未割り当てのドライブをクラスタに追加して、新しいクラスタの作成後に Available タブに表示できます。

.手順
. NetApp Element Management > Cluster * の順に選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ * ドライブ * （ Drives * Drives ） ] サブタブを選択します。
. [ アクティブ（ * Active ） ] ビューを選択します。
. システムで現在アクティブになっているドライブの詳細を表示します。
+
ドライブ ID 、各ドライブの容量とステータス、ドライブが配置されているノードに関する情報などの情報を表示できます。





== ドライブを取り外します

NetApp Element Management 拡張ポイントを使用して、クラスタからドライブを削除できます。この操作は、クラスタの容量を減らしたり、サービス寿命の終わりに近づいているドライブの交換準備を行ったりするときに実行できます。削除したドライブはオフラインになります。ドライブをクラスタから削除する前に、ドライブ上のデータがすべて削除され、クラスタ内の他のドライブに移行されます。システム内の他のアクティブドライブへのデータ移行には、クラスタの容量利用率とアクティブな I/O に応じて、数分から 1 時間かかります。

Failed 状態のドライブを削除しても ' ドライブは Available 状態または Active 状態には戻りませんそのドライブはクラスタで使用できなくなります。

.手順
. NetApp Element Management > Cluster * の順に選択します。
. 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。
. ドロップダウンリストから「 * All * 」を選択して、ドライブの完全なリストを表示します。
. 次の手順でドライブを削除します。
+
.. 削除する各ドライブのチェックボックスを選択します。
.. ドライブの取り外し * をクリックします。


. 操作を確定します。
+

NOTE: アクティブドライブを削除するための十分な容量がない場合は、ドライブの削除を確定した時点でエラーメッセージが表示されます。


