---
sidebar: sidebar 
permalink: vcp_reference_reports_alert_errors.html 
summary: 次に、システムアラートのリストを示します。このリストは、 NetApp Element Plug-in for vCenter Server のレポートページを使用して、クラスタの稼働状況を示す情報、警告、またはエラーです。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= システムアラートのリスト
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
NetApp Element Management 拡張ポイントの * Reporting > Alerts * ページに、各アラートのエラーコードが表示されます。エラーコードは、アラートが発生したシステムのコンポーネントおよびアラートが生成された理由を判断する場合に役立ちます。

以下に、各種のシステムアラートの一覧を示します。

* * authenticationServiceFault * ： 1 つ以上のクラスタノードの認証サービスが想定どおりに機能していません。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* *availableVirtualNetworkIPAddressesLow* ： IP アドレスブロック内の仮想ネットワークアドレスの数が少なくなっています。
+
* 解決するには * ：仮想ネットワークアドレスのブロックに IP アドレスを追加します。

* * blockClusterFull * ： 1 つのノードの損失をサポートするのに十分な空きブロックストレージスペースがありません。クラスタフルのレベルの詳細については、 GetClusterFullThreshold API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。
+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。


+
* 解決するには * ：ボリュームを削除するか、ストレージ・クラスタに別のストレージ・ノードを追加します。

* *blocksDegraded*: 障害が発生したため、ブロック・データが完全に複製されていません。
+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | アクセス可能なブロックデータの完全なコピーは 2 つだけです。 


| エラー | アクセス可能なブロックデータの完全なコピーは 1 つだけです。 


| 重要 | ブロックデータの完全なコピーにはアクセスできません。 
|===
+

NOTE: 警告ステータスは、トリプル Helix システムでのみ発生します。

+
* 解決方法 * ：オフラインのノードやブロックサービスをリストアするか、ネットアップサポートにお問い合わせください。

* *blockServiceTooFull* ：ブロックサービスが大量のスペースを使用しています。
+
* 解決方法 * ：プロビジョニング済み容量を追加します。

* * ブロック・サービスが正常でないことが検出されました：
+
** 重大度 = 警告：対処は行われません。この警告期間は、 cTimeUntilBSIsKilledMSec = 330000 ミリ秒で期限切れになります。
** 重大度 = エラー：データの運用停止処理が自動的に実行され、他の正常なドライブにデータが再レプリケートされます。
** 重大度 = 重大：複数のノードで障害ブロックサービスが発生していますが、レプリケーション数以上になっています（ Double Helix の場合は 2 ）。データを使用できないため、ビンの同期が完了しません。


+
* 解決するには * ：ネットワーク接続の問題とハードウェアエラーを確認してください。特定のハードウェアコンポーネントで障害が発生した場合は、それ以外の障害が発生します。この障害は、ブロックサービスにアクセスできるかサービスが運用停止されると解消されます。

* * clockSkewExeedFaultThreshold * ：クラスタマスターとトークンを提供しているノードとの間の時間差が推奨されるしきい値を超えています。ストレージクラスタは、ノード間の時間スキューを自動的に修正できません。
+
* 解決する場合 * ：インストール時のデフォルトではなく、ネットワーク内部の NTP サーバを使用します。内部の NTP サーバを使用している場合は、ネットアップサポートにお問い合わせください。

* * clusterCannotSync* ：スペース不足のため、オフラインのブロックストレージドライブ上のデータをアクティブなドライブと同期することはできません。
+
* 解決するには * ：ストレージを追加してください。

* * clusterFull * ：ストレージクラスタに空きストレージスペースがなくなりました。
+
* 解決するには * ：ストレージを追加してください。

* * clusterIOPSReOverProvisioned * ：クラスタ IOPS がオーバープロビジョニングされています。QoS の最小 IOPS の合計が、クラスタの想定 IOPS を上回っています。すべてのボリュームで同時に最小 QoS を維持することができません。
+
* 解決する * ：ボリュームの最小 QoS IOPS 設定を引き下げます。

* * disableDriveSecurityFailed* ：クラスタはドライブセキュリティ（保存データの暗号化）を有効にするように設定されていませんが、少なくとも 1 つのドライブでドライブセキュリティが有効になっているため、それらのドライブでドライブセキュリティを無効にできませんでした。この障害の重大度は「 Warning 」です。
+
* 解決方法 * ：ドライブのセキュリティを無効にできなかった理由について、障害の詳細を確認してください。考えられる原因は次のとおりです。

+
** 暗号化キーを取得できませんでした。キーまたは外部キーサーバへのアクセスに関する問題を調査してください。
** ドライブで無効化処理に失敗した場合は、間違ったキーが取得されていないかどうかを確認してください。


+
どちらでもない場合は、ドライブの交換が必要となる可能性があります。正しい認証キーを指定してもセキュリティが無効にならないドライブに対して、リカバリを試みることができます。この処理を実行するには、ドライブの状態を Available に変更してシステムから取り外し、ドライブで完全消去を実行してから Active に戻します。

* * disconnectedClusterPair * ：クラスタペアが切断されているか、正しく設定されていません。
+
* 解決方法 * ：クラスタ間のネットワーク接続を確認してください。

* * disconnectedRemoteNode * ：リモートノードが切断されているか、正しく設定されていません。
+
* 解決するには * ：ノード間のネットワーク接続を確認してください。

* * disconnectedSnapMirrorEndpoint * ：リモート SnapMirror エンドポイントが切断されているか、正しく設定されていません。
+
* 解決方法 * ：クラスタとリモート SnapMirrorEndpoint の間のネットワーク接続を確認してください。

* * driveAvailable * ：クラスタ内に 1 つ以上のドライブがあります。通常は、すべてのクラスタにすべてのドライブが追加されており、利用可能な状態のドライブはありません。この問題が予期せずに発生する場合は、ネットアップサポートにお問い合わせください。
+
* 解決方法 * ：ストレージクラスタに利用可能なドライブをすべて追加します。

* * driveFailed * ：次のいずれかの状態を示す 1 つ以上のドライブで障害が発生した場合、クラスタはこのエラーを返します。
+
** ドライブマネージャがドライブにアクセスできません。
** スライスサービスまたはブロックサービスで障害が発生した回数が多すぎます。おそらくドライブの読み取りまたは書き込みの失敗が原因で再起動できません。
** ドライブがありません。
** ノードのマスターサービスにアクセスできません（ノード内のすべてのドライブが見つからないか障害状態であるとみなされます）。
** ドライブがロックされており、そのドライブの認証キーを取得できません。
** ドライブがロックされているためロック解除処理が失敗します。


+
* 解決するため * ：

+
** ノードのネットワーク接続を確認してください。
** ドライブを交換します。
** 認証キーが使用可能であることを確認します。


* * driveHealthFault* ：ドライブのヘルスチェックに失敗したため、ドライブの機能が低下しました。この障害には、 Critical 重大度レベルがあります。
+
** シリアル付きドライブ： < シリアル番号 > 、スロット： < ノードスロット >< ドライブスロット > 、 SMART 全体のヘルスチェックに失敗しました。


+
* 解決するには * ：ドライブを交換します。

* * driveWearFault * ：ドライブの残存寿命がしきい値を下回っていますが、まだ機能しています。このエラーには、重大度レベルとして「重大」と「警告」の 2 つがあります。
+
** シリアル付きドライブ： <serial number> in slot ： <node slot><drive slot> には、重大な摩耗度レベルがあります。
** Serial Number > in slot ： < ノードスロット >< ドライブスロット > のドライブの摩耗リザーブが少ない。


+
* ：この問題を解決するには、ドライブをすぐに交換してください。

* * duplicateClusterMasterCandidates * ：複数のストレージクラスタマスター候補が検出されました。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * enableDriveSecurityFailed * ：クラスタはドライブのセキュリティ（保存中のデータの暗号化）を必要とするように設定されていますが、少なくとも 1 つのドライブでドライブのセキュリティを有効にできませんでした。この障害の重大度は「 Warning 」です。
+
* 解決方法 * ：ドライブのセキュリティを有効にできなかった理由について、障害の詳細を確認してください。考えられる原因は次のとおりです。

+
** 暗号化キーを取得できませんでした。キーまたは外部キーサーバへのアクセスに関する問題を調査してください。
** ドライブで有効化処理に失敗した場合は、間違ったキーが取得されていないかどうかを確認してください。
+
どちらでもない場合は、ドライブの交換が必要となる可能性があります。



+
正しい認証キーを指定してもセキュリティが有効にならないドライブに対して、リカバリを試みることができます。この処理を実行するには、ドライブの状態を Available に変更してシステムから取り外し、ドライブで完全消去を実行してから Active に戻します。

* * ensembleDegraded * ： 1 つ以上のアンサンブルノードでネットワーク接続または電源が失われました。
+
* 解決するには * ：この問題を解決するには、ネットワーク接続または電源を復旧してください。

* * 例外 * ：通常の故障以外の故障が報告されました。これらの障害は、障害キューから自動的に消去されることはありません。
+
* 解決方法 * 詳しくは、ネットアップサポートにお問い合わせください。

* * SpaceTooFull* ：データ書き込み要求に失敗したブロックサービスが応答していません。スライスサービスが失敗した書き込みを格納するためのスペースが不足します。
+
* ：この問題を解決するには、書き込みを正常に続行し、失敗した書き込みスペースをスライスサービスからフラッシュできるように、ブロックサービス機能をリストアしてください。

* * fanSensor * ：ファンセンサーに障害が発生しているか、ファンセンサーがありません。
+
* 解決するには * ：この問題を解決するには、故障したハードウェアを交換します。

* * fibreChannelAccessDegraded * ： Fibre Channel ノードがストレージ IP を介してストレージクラスタ内の他のノードに一定期間応答していません。この状態になると、ノードは応答していないと判断され、クラスタ障害が生成されます。
+
* 解決するには * ：ネットワーク接続を確認してください。

* * fibreChannelAccessUnavailable * ：すべての Fibre Channel ノードが応答していません。ノード ID が表示されます。
+
* 解決するには * ：ネットワーク接続を確認してください。

* * fibreChannelActiveIXL * ： iXL Nexus の数は、 Fibre Channel ノードあたり 8 、 000 のアクティブセッションの上限に近づいています。
+
** ベストプラクティスの上限は 5500 です。
** 警告の上限は 7500 です。
** 上限（必須ではない）は 8192 です。


+
* 解決策 * ： iXL Nexus の数を、ベストプラクティスの上限である 5500 未満に削減する。

* * fibreChannelConfig * ：このクラスタエラーは、次のいずれかの状態を示します。
+
** PCI スロットに予期しないファイバチャネルポートがあります。
** 想定外の Fibre Channel HBA モデルが使用されています。
** Fibre Channel HBA のファームウェアに問題があります。
** Fibre Channel ポートがオンラインではありません。
** Fibre Channel パススルーを設定している永続的な問題があります。


+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * fibreChannelIOPS * ：合計 IOPS 数がクラスタ内の Fibre Channel ノードの IOPS 制限に近づいています。制限は次のとおりです。
+
** FC0025 ： 450 、 000 IOPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）
** FCN001 ： 625K OPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）。


+
* ：この問題を解決するには、使用可能なすべての Fibre Channel ノードに負荷を分散します。

* * fibreChannelStaticIxL * ： iXL Nexus カウントは、 Fibre Channel ノードあたりのサポートされる静的セッションの上限である 16000 に近づいています。
+
** ベストプラクティスの上限は 11000 です。
** 警告制限は 15000 です。
** 最大制限（強制）は 16384 です。


+
* 解決するには * ：この問題を解決するには、 iXL Nexus のカウントをベストプラクティスの上限である 11000 未満に減らしてください。

* *fileSystemCapacityLow *: いずれかのファイルシステムに十分な領域がありません。
+
* 解決するには * ：ファイルシステムに容量を追加してください。

* * fipsDrivesMismatch * ： FIPS 非対応ストレージノードに FIPS 非対応ドライブが物理的に挿入されているか、 FIPS 非対応ストレージノードに FIPS ドライブが物理的に挿入されています。ノードごとにエラーが生成され、影響を受けるすべてのドライブが表示されます。
+
* 解決するには * ：この問題を解決するには、該当するドライブを取り外すか交換してください。

* * fipsDrivesOutOfCompliance * ： FIPS ドライブ機能が有効になったあとに保存データの暗号化が無効になったことが検出されました。このエラーは、 FIPS ドライブ機能が有効になっていて、 FIPS 非対応のドライブまたはノードがストレージクラスタに配置されている場合にも生成されます。
+
* 解決するには * ：保存データの暗号化を有効にするか、 FIPS 非対応のハードウェアをストレージクラスタから取り外してください。

* * fipsSelfTestFailure * ： FIPS サブシステムがセルフテスト中に障害を検出しました。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * hardwareConfigMismatch * ：このクラスタエラーは、次のいずれかの状態を示します。
+
** 構成がノード定義と一致しません。
** このタイプのノードに対して正しくないドライブサイズが使用されています。
** サポート対象外のドライブが検出されました。原因としては、インストールされている Element のバージョンがこのドライブを認識しないことが考えられます。このノードで Element ソフトウェアを更新することを推奨します。
** ドライブファームウェアが一致しません。
** ドライブの暗号化対応がノードと一致しません。


+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* *idPCertificateExpiration* ：サードパーティのアイデンティティプロバイダ（ IdP ）で使用するクラスタのサービスプロバイダ SSL 証明書の有効期限が近づいているか、すでに有効期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。
+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | 証明書は 30 日以内に期限切れになります。 


| エラー | 証明書は 7 日以内に期限切れになります。 


| 重要 | 証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。 
|===
+
* 解決するには * ：この問題を解決するには、有効期限が切れる前に SSL 証明書を更新してください。更新された SSL 証明書を提供するには、「 UpdateIdpConfiguration 」 API メソッドを「 re freshCertificateExpirationTime=true 」とともに使用します。

* * inconsistentBondModes * ： VLAN デバイス上のボンディングモードがありません。想定されるボンディングモードと使用中のボンディングモードが表示されます。
* *inconsistentInterfaceConfiguration*: インターフェイス設定が矛盾しています。
+
* ：この問題を解決するには、ストレージクラスタ内のノードインターフェイスの設定が同じであることを確認してください。

* * inconsistentMtus * ：このクラスタエラーは、次のいずれかの状態を示しています。
+
** Bond1G mismatch ： Bond1G インターフェイス間で異なる MTU が設定されています。
** Bond10G mismatch ： Bond10G インターフェイス間で異なる MTU が設定されています。


+
該当するノードと関連付けられている MTU 値が表示されます。

* *inconsistentRoutingRules* ：このインターフェイスのルーティングルールが矛盾しています。
* *inconsistentSubnetMas* ： VLAN デバイス上のネットワークマスクが、内部的に記録された VLAN のネットワークマスクと一致しません。想定されるネットワークマスクと使用中のネットワークマスクが表示されます。
* * incorrectBondPortCount * ：ボンドポートの数が正しくありません。
* * invalidConfiguredFibreChannelNodeCount * ：想定されている 2 つの Fibre Channel ノード接続のいずれかがデグレードされています。この障害は、 Fibre Channel ノードが 1 つしか接続されていない場合に発生します。
+
* 解決するには * ：クラスタネットワークの接続状態とケーブル配線を確認し、障害が発生したサービスがないか確認してください。ネットワークやサービスに問題がない場合は、ネットアップサポートに連絡して Fibre Channel ノードを交換してください。

* *irqBalanceFailed*: 割り込みのバランスをとる際に例外が発生しました。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * kmipCertificateFault * ：
+
** ルート認証局（ CA ）証明書の有効期限が近づいています。
+
* 解決するには * ：この問題を解決するには、有効期限が 30 日以上ある新しい証明書をルート CA から取得し、 ModifyKeyServerKmip を使用して更新されたルート CA 証明書を提供します。

** クライアント証明書の有効期限が近づいています。
+
* 解決するには * ：この問題を解決するには、 GetClientCertificateSigningRequest を使用して新しい CSR を作成し、新しい有効期限まで 30 日以上あることを確認して署名し、 ModifyKeyServerKmip を使用して期限切れになる KMIP クライアント証明書を新しい証明書に置き換えます。

** ルート認証局（ CA ）証明書の有効期限が切れています。
+
* 解決するには * ：この問題を解決するには、有効期限が 30 日以上ある新しい証明書をルート CA から取得し、 ModifyKeyServerKmip を使用して更新されたルート CA 証明書を提供します。

** クライアント証明書の期限が切れています。
+
*: この問題を解決するには、「 GetClientCertificateSigningRequest 」を使用して新しい CSR を作成し、新しい有効期限が 30 日以上経過していることを確認して署名し、「 modyKeyServerKmip 」を使用して期限切れの KMIP クライアント証明書を新しい証明書に置き換えます。

** ルート認証局（ CA ）証明書のエラーです。
+
* 解決するには * ：この問題を解決するには、正しい証明書が提供されていることを確認し、必要に応じてルート CA から証明書を再取得します。正しい KMIP クライアント証明書をインストールするには、「 modyKeyServerKmip 」を使用します。

** クライアント証明書エラーです。
+
* 解決する * ：この問題を解決するには、正しい KMIP クライアント証明書がインストールされていることを確認してください。クライアント証明書のルート CA が EKS にインストールされている必要があります。正しい KMIP クライアント証明書をインストールするには、「 modyKeyServerKmip 」を使用します。



* * kmipServerFault * ：
+
** 接続に失敗しました
+
* 解決するには * ：この問題を解決するには、外部キーサーバが稼働しており、ネットワーク経由でアクセスできることを確認してください。「 TestKeyServerKimp 」と「 TestKeyProviderKmip 」を使用して、接続をテストします。

** 認証に失敗しました
+
* 解決するには * ：この問題を解決するには、正しいルート CA および KMIP クライアント証明書が使用されていること、および秘密鍵と KMIP クライアント証明書が一致することを確認してください。

** サーバエラーです
+
* 解決するには * ：この問題を解決するには、エラーの詳細を確認してください。エラーによっては、外部キーサーバでのトラブルシューティングが必要になる場合があります。



* * memyEccThreshold * ：修正可能な ECC エラーまたは修正不可能な ECC エラーが多数検出されました。Error タイプの重大度が返された場合は、 DIMM の障害が原因である可能性があります。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * memoryUsageThreshold * ：メモリ使用量が正常値を上回っています。この問題では、緊急性に基づいて次の重大度が使用されます。
+

NOTE: エラーの詳細については、「詳細」の見出しを参照してください。

+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | システムメモリが不足しています。 


| エラー | システムメモリが非常に少なくなっています。 


| 重要 | システムメモリが完全に消費されています。 
|===
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * メタデータ ClusterFull * ： 1 つのノード損失をサポートするのに十分なメタデータストレージスペースがありません。クラスタフルレベルの詳細については、「 GetClusterFullThreshold 」 API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。
+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。データをパージまたは削除するか、ノードを追加します。


+
* 解決するには * ：ボリュームを削除するか、ストレージ・クラスタに別のストレージ・ノードを追加します。

* *mtuCheckFailure*: ネットワークデバイスが適切な MTU サイズに設定されていません。
+
* を解決する場合 * ：すべてのネットワークインターフェイスとスイッチポートでジャンボフレームが設定されていることを確認してください（ MTU が最大 9 、 000 バイト）。

* *networkConfig*: このクラスタ障害は、次のいずれかの状態を示します。
+
** 想定されるインターフェイスが存在しません。
** インターフェイスが重複しています。
** 設定されたインターフェイスが停止しています。
** ネットワークの再起動が必要です。


+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * noAvailableVirtualNetworkIPAddresses* ： IP アドレスのブロックに使用可能な仮想ネットワークアドレスがありません。
+
[listing]
----
 virtualNetworkID # TAG(###) has no available storage IP addresses. Additional nodes cannot be added to the cluster.
----
+
* 解決するには * ：仮想ネットワークアドレスのブロックに IP アドレスを追加します。

* * nodeHardwareFault （ネットワークインターフェイス <name> が停止しているかケーブルが接続されていません） * ：ネットワークインターフェイスが停止しているか、ケーブルが接続されていません。
+
* 解決するには * ：ノードのネットワーク接続を確認してください。

* * nodeHardwareFault （ Drive encryption Capable state mismatches node 's encryption capable state for the drive in slot <node slot><drive slot> ） * ：ドライブが、搭載されているストレージノードと暗号化機能を一致しません。
* * nodeHardwareFault （このノードタイプのスロット >< ドライブスロット > のドライブスロット > にあるドライブの < ドライブタイプ > ドライブサイズ < 実際のサイズ > が正しくありません。 <expected size> ） * ：ストレージノードにこのノードのサイズが正しくないドライブが含まれています。
* * nodeHardwareFault （サポートされていないドライブがスロット <node slot><drive slot> で検出されました。ドライブの統計と健全性情報が使用できません） * ：ストレージノードに、サポートされないドライブが含まれています。
* * nodeHardwareFault （スロット < ノードスロット >< ドライブスロット > のドライブでファームウェアバージョン < 想定されるバージョン > を使用している必要がありますが、サポートされていないバージョン < 実際のバージョン > を使用しています） * ：ストレージノードでサポートされていないファームウェアバージョンを実行しているドライブが含まれています。
* * nodeMaintenanceMode * ：ノードがメンテナンスモードになりました。この問題では、緊急性に基づいて次の重大度が使用されます。
+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | ノードがまだメンテナンスモードになっていることを示します。 


| エラー | メンテナンスモードを無効にできなかったことを示します。通常は、スタンバイが失敗したかアクティブなスタンバイが原因です。 
|===
+
* 解決するには * ：メンテナンスが完了したらメンテナンスモードを無効にしてください。エラーレベルの問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * nodeOffline * ： Element ソフトウェアが指定したノードと通信できません。ネットワーク接続を確認してください。
* * notUsingLACpBondMode * ： LACP ボンディングモードが設定されていません。
+
* 解決方法 * ：ストレージノードの導入時は LACP ボンディングを使用してください。 LACP を有効にして適切に設定していないと、クライアントでパフォーマンスの問題が発生する可能性があります。

* * ntpServerUnreachable* ：ストレージクラスタが指定された NTP サーバと通信できません。
+
* 解決する *: NTP サーバ、ネットワーク、およびファイアウォールの設定を確認します。

* * ntpTimeNotInSync * ：ストレージクラスタと指定された NTP サーバの時刻との差が大きすぎます。ストレージクラスタはこの時間差を自動的に修正できません。
+
* 解決する場合 * ：インストール時のデフォルトではなく、ネットワーク内部の NTP サーバを使用します。内部の NTP サーバを使用しても問題が維持される場合は、ネットアップサポートにお問い合わせください。

* * nvramDeviceStatus * ： NVRAM デバイスでエラーが発生しているか、障害が発生しているか、または障害が発生しています。この問題には次の重大度があります。
+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | ハードウェアによって警告が検出されました。この状態は、温度警告などの一時的なものです。* nvmetimeError * nvmetimeStatus * energySourceLifetimeStatus * energySourceTemperatureStatus * warningThresholdExceeded 


| エラー | ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。警告レベルエラーに加えて返されたエラー： * NVRAM デバイスマウントポイントが存在しません。* NVRAM デバイスパーティションが存在しません。* NVRAM デバイスパーティションは存在しますが、マウントされていません。 


| 重要 | ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。* persistenceLost* armStatusSaveNArmed * csaveStatusError 
|===
+
* 解決方法 * ：ノード内の障害が発生したハードウェアを交換します。それでも問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * powerSupplyError * ：このクラスタエラーは、次のいずれかの状態を示します。
+
** 電源装置がありません。
** 電源装置で障害が発生しました。
** 電源装置の入力が見つからないか、範囲外です。
+
* 解決する場合 * ：冗長電源がすべてのノードに供給されていることを確認してください。ネットアップサポートにお問い合わせください。



* * provisionedSpaceTooFull * ：クラスタの全体的なプロビジョニング済み容量がいっぱいです。
+
* 解決方法 * ：プロビジョニング済みスペースを追加するか、またはボリュームを削除およびパージします。

* * remoteRepAsyncDelayExceeded * ：レプリケーションに設定されている非同期遅延を超えています。クラスタ間のネットワーク接続を確認してください。
* * remoteRepClusterFull * ：ターゲットストレージクラスタがいっぱいのため、ボリュームがリモートレプリケーションを停止しました。
+
* 解決方法 * ：ターゲットストレージクラスタの空き容量を増やしてください。

* * remoteRepSnapshotClusterFull * ：ターゲットストレージクラスタがいっぱいのため、ボリュームが Snapshot のリモートレプリケーションを停止しました。
+
* 解決方法 * ：ターゲットストレージクラスタの空き容量を増やしてください。

* * remoteRepSnapshotsExceededLimit * ：ターゲットストレージクラスタのボリュームが Snapshot の上限を超えたため、ボリュームが Snapshot のリモートレプリケーションを停止しました。
+
* 解決するには * ：ターゲットストレージクラスタの Snapshot 数の制限を引き上げます。

* * scheduleActionError * ： 1 つ以上のスケジュール済みアクティビティが実行されましたが、失敗しました。スケジュールされたアクティビティが再び実行されて成功するか、スケジュールされたアクティビティが削除されるか、またはアクティビティが一時停止されて再開されると、障害はクリアされます。
* * sensorReadingFailed* ：ベースボード管理コントローラ（ BMC ）のセルフテストに失敗したか、センサーが BMC と通信できませんでした。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * serviceNotRunning * ：必要なサービスが実行されていません。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * sliceServiceTooFull * ：スライスサービスに割り当てられたプロビジョニング済み容量が少なすぎます。
+
* 解決方法 * ：プロビジョニング済み容量を追加します。

* * sliceServiceUnhealthy * ：スライスサービスが正常に動作していないことがシステムによって自動的に停止します。
+
** 重大度 = 警告：対処は行われません。この警告期間は 6 分後に終了します。
** 重大度 = エラー：データの運用停止処理が自動的に実行され、他の正常なドライブにデータが再レプリケートされます。


+
* 解決するには * ：ネットワーク接続の問題とハードウェアエラーを確認してください。特定のハードウェアコンポーネントで障害が発生した場合は、それ以外の障害が発生します。スライスサービスにアクセスできるかサービスが運用停止されると、障害は解消されます。

* * sshEnabled * ：ストレージクラスタ内の 1 つ以上のノードで SSH サービスが有効になっています。
+
* 解決方法 * ：適切なノードで SSH サービスを無効にするか、ネットアップサポートにお問い合わせください。

* * sslCertificateExpiration * ：このノードに関連付けられている SSL 証明書の有効期限が近づいているか有効期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。
+
[cols="25,75"]
|===
| 重大度 | 説明 


| 警告 | 証明書は 30 日以内に期限切れになります。 


| エラー | 証明書は 7 日以内に期限切れになります。 


| 重要 | 証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。 
|===
+
* 解決するため * ： SSL 証明書を更新してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * strandedCapacity * ： 1 つのノードがストレージクラスタの容量の半分以上を占めます。データの冗長性を維持するために、最大のノードの容量がシステムによって削減され、ブロック容量の一部が孤立（使用されない）状態になります。
+
* 解決するには * ：既存のストレージノードにドライブを追加するか、クラスタにストレージノードを追加してください。

* * tempSensor * ：温度センサーが通常よりも高い温度を報告しています。この問題は、 powerSupplyError または fanSensor とともに発生する可能性があります。
+
* 解決するために * ：ストレージクラスタの近くに通気を妨げる障害物がないか確認してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * アップグレード * ：アップグレードが 24 時間以上実行中です。
+
* 解決方法 * ：アップグレードを再開するか、ネットアップサポートにお問い合わせください。

* * 対応していないサービス * ：サービスが応答しなくなりました。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * virtualNetworkConfig * ：このクラスタ障害は、次のいずれかの条件を示します。
+
** インターフェイスが存在しません。
** インターフェイス上のネームスペースが正しくありません。
** ネットマスクが正しくありません。
** IP アドレスが正しくありません。
** インターフェイスが稼働していません。
** ノード上に不要なインターフェイスがあります。


+
* 解決方法 * ：ネットアップサポートにお問い合わせください。

* * volumesDegraded * ：セカンダリボリュームのレプリケーションと同期が完了していません。このメッセージは、同期が完了するとクリアされます。
* * volumesOffline * ：ストレージクラスタ内の 1 つ以上のボリュームがオフラインです。volumeDegraded エラーも発生します。
+
* 解決方法 * ：ネットアップサポートにお問い合わせください。



[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

