---
sidebar: sidebar 
permalink: vcp_task_create_manage_initiators.html 
summary: プラグインを使用してイニシエータを作成および管理できます。 
keywords: netapp, storage, inititators, vcp, vcenter, element 
---
= イニシエータを作成および管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
イニシエータはクライアントとボリューム間の通信のエントリポイントとして機能し、外部クライアントからクラスタ内のボリュームへのアクセスを可能にします。

イニシエータを作成、編集、削除したり、管理やボリュームアクセスを簡単にするためにわかりやすいエイリアスを指定したりできます。ボリュームアクセスグループに追加されたイニシエータは、グループ内のすべてのボリュームにアクセスできるようになります。

.オプション（ Options ）
* <<Create an initiator>>
* <<Edit an initiator>>
* <<Add initiators to an access group>>
* <<Delete an initiator>>




== イニシエータを作成します

iSCSI イニシエータまたは Fibre Channel イニシエータを作成し、オプションでエイリアスを割り当てることができます。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Initiators * （イニシエータ * ） ] サブタブを選択します。
. イニシエータの作成 * を選択します。
. 単一のイニシエータを作成するには、
+
.. [ * 単一イニシエータの作成 * ] を選択します。
.. IQN または WWPN * フィールドにイニシエータの IQN または WWPN を入力します。
+
イニシエータ IQN の有効な形式は、「 iqn.yyyy-mm 」です。 y と m は数字で、続けて任意の文字列を指定します。使用できる文字は、数字、小文字のアルファベット、ピリオド（ ` ）、コロン（ ` ）、またはダッシュ（「 - 」）だけです。形式の例を次に示します。

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+
Fibre Channel イニシエータ WWPN の有効な形式は、「 :AA:BB:CC:dd:11:22:33:44' または「 AabBCCdd11223344 」です。形式の例を次に示します。

+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
.. [* エイリアス ] フィールドにイニシエータのフレンドリ名を入力します。


. 複数のイニシエータを作成するには
+
.. [Create Multiple Initiators] を選択します。
.. 次のいずれかを実行します。
+
*** ［ * ホストのスキャン * ］ をクリックして、 NetApp Element クラスタに定義されていないイニシエータ値を vSphere ホストでスキャンします。
*** IQN または WWPN のリストをテキストボックスに入力し、「 * Add Initiators * 」を選択します。


.. （オプション） [* エイリアス ] 見出しの下で、各エントリのフィールドを選択してエイリアスを追加します。
.. （オプション）必要に応じて、リストからイニシエータを削除します。


. OK をクリックしてイニシエータを作成します。




== イニシエータを編集します

既存のイニシエータのエイリアスを変更するか、既存のエイリアスがない場合はエイリアスを追加できます。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Initiators * （イニシエータ * ） ] サブタブを選択します。
. 編集するイニシエータのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. [* Alias* ] フィールドに、イニシエータの新しいエイリアスを入力します。
. [OK] をクリックします。




== アクセスグループにイニシエータを追加します

アクセスグループにイニシエータを追加すると、そのイニシエータはボリュームアクセスグループ内のボリュームに CHAP 認証なしでアクセスできるようになります。ボリュームアクセスグループに追加されたイニシエータは、そのボリュームアクセスグループ内のすべてのボリュームにアクセスできます。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Initiators * （イニシエータ * ） ] サブタブを選択します。
. アクセスグループに追加するイニシエータのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * アクセスグループに追加 * を選択します。
. [ アクセスグループに追加 *] ダイアログボックスで、ドロップダウンリストからアクセスグループを選択します。
. [OK] をクリックします。




== イニシエータを削除します

不要になったイニシエータを削除できます。イニシエータを削除すると、関連付けられているすべてのボリュームアクセスグループから削除されます。イニシエータを使用した接続は、接続をリセットするまでは有効なままです。

.手順
. NetApp Element 管理 > 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Initiators * （イニシエータ * ） ] サブタブを選択します。
. 削除するイニシエータのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。


[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

