---
sidebar: sidebar 
permalink: vcp_concept_linkedmode.html 
summary:  
keywords: netapp, vcp, element, plugin, plug-in, linked mode 
---
= リンクモードおよびプラグイン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element Plug-in for VMware vCenter Serverでは、vCenterリンクモードを使用して他のvCenter Serverのクラスタリソースを管理することができます。

Element Plug-in でストレージクラスタを管理できるのは、デスティネーション vCenter の Web クライアントにログインしている場合のみです。

vSphere リンクモード環境でストレージクラスタの管理をセットアップするには、次の手順を使用してストレージクラスタを手動で追加します。

.手順
. プラグインを使用するリンクモード環境内の各 vCenter Server にプラグインを登録します。
. リンクされた各 vCenter Server の vSphere Web Client に一度ログインします。
+
ログインすると、 Web Client にプラグインがインストールされます。

. ストレージクラスタを管理するデスティネーション vCenter の Web クライアントにログインします。
. ストレージクラスタを Element Plug-in のインベントリに追加します。


リンクモードで vCenter1 と vCenter2 を、ストレージ cluster1 とストレージ cluster2 をそれぞれ設定した。cluster1 、 vCenter2 の管理を許可して cluster2 を管理します。ストレージクラスタ管理を設定するには、各 vCenter Server にプラグインを登録したあとで、次の手順を実行します。

. vCenter1 Web クライアントにログインします。
. cluster1 を vCenter1 Web クライアントから管理するには、 cluster1 を Element Plug-in のインベントリに追加します。
. vCenter2 Web クライアントにログインします。
. cluster2 を vCenter2 Web クライアントから管理するには、 cluster2 を Element Plug-in のインベントリに追加します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

