---
sidebar: sidebar 
permalink: vcp_task_protect_snapshots_group.html 
summary: ボリュームセットのグループ Snapshot を作成して、各ボリュームのメタデータのポイントインタイムコピーを保持します。 
keywords: netapp, hci, vcp, vcenter, element, protect, snapshots, clone, backup, amazon, s3, openstack, swift 
---
= vCenter Server でグループ Snapshot を作成および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
関連する一連のボリュームのグループ Snapshot を作成して、各ボリュームのメタデータのポイントインタイムコピーを保持できます。グループ Snapshot をバックアップまたはロールバックとして使用して、ボリュームグループの状態を希望する時点にリストアすることができます。

.オプション（ Options ）
*  a group snapshot
*  group snapshot details
*  volumes from a group snapshot
*  back volumes to a group snapshot
*  a group snapshot




== グループ Snapshot を作成します

ボリュームグループの Snapshot を今すぐ作成するか、スケジュールを作成してボリュームグループの Snapshot があとで自動的に作成されるようにすることができます。1 つのグループ Snapshot には、一度に最大 32 個のボリュームの Snapshot を含めることができます。

グループ Snapshot のレプリケーション設定または保持期間は、あとから変更することができます。指定した保持期間は、新しい間隔の開始時点からの期間です。保持期間には、（ Snapshot の作成時間からではなく）現在の時刻からの期間を指定できます。間隔は、分、時間、および日単位で指定できます。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 管理 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Volumes （ボリューム） ] サブタブをクリックします。
. 「 * Active * 」ビューで、 Snapshot に使用するボリュームのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * Create Group Snapshot * （グループ Snapshot の作成）を選択します。
. （オプション） Create Group Snapshot （グループ Snapshot の作成）ダイアログボックスで、スナップショットの名前を入力します。
+

TIP: わかりやすい名前のベストプラクティスを使用してください。これは、環境で複数のクラスタや vCenter Server を使用している場合に特に重要です。グループ Snapshot の名前を入力しなかった場合、デフォルトでは Snapshot の作成日時が名前として使用されます。

. （オプション） * ペアリング時に Snapshot をレプリケーションに含める * チェックボックスをオンにして、親ボリュームがペアリングされたときに Snapshot をレプリケートするようにします。
. Snapshot の保持期間として次のいずれかを選択します。
+
** * 永続的に保持 * ： Snapshot をシステム上に無期限に保持します。
** * 保存期間の設定 * ：システムがスナップショットを保持する期間（日数、時間、または分）を指定します。
+

NOTE: 保持期間には、現在の時刻からの期間を選択します。（保持期間は Snapshot の作成時間からは計算されません）。



. 単一の即時スナップショットを作成するには、 * グループスナップショットを今すぐ作成 * を選択します。
. スケジュールを設定してあとで Snapshot を作成するには、次の手順を実行します。
+
.. Create snapshot schedule * （スナップショットスケジュールの作成）を選択します。
.. スケジュール名を入力します。
.. スケジュールタイプを選択し、スケジュールの詳細を設定します。
.. （オプション）定期的にスケジュールされたスナップショットを繰り返すには、 *RecurrentSchedule* のチェックボックスをオンにします。


. [OK] をクリックします。




== グループ Snapshot の詳細を表示します

必要に応じて、 Snapshot が追加されたことを確認できます。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ グループスナップショット * （ Group Snapshots * ） ] サブタブをクリックします。
. Snapshot の詳細を確認します。
+
** * Create date * ：グループ Snapshot が作成された日時。
** * Status * ： NetApp Element ソフトウェアを実行しているリモートクラスタ上の Snapshot のステータスを表示します。
+
*** * 準備中 * ： Snapshot は使用準備中で、まだ書き込みができません。
*** * done * ：この Snapshot は準備が完了しており、現在使用可能です。
*** * Active * ：スナップショットはアクティブブランチです。


** * ボリューム数 * ：グループ Snapshot 内のボリュームの数。






== グループ Snapshot からボリュームをクローニングします

ボリュームのグループをポイントインタイムのグループ Snapshot からクローニングできます。作成したボリュームは、システム内の他のボリュームと同様に使用できます。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ グループスナップショット * （ Group Snapshots * ） ] サブタブをクリックします。
. ボリュームのクローンに使用するグループ Snapshot のチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * Clone Volumes from Group Snapshot * （グループ Snapshot からのボリュームのクローン）を選択します。
. （オプション）グループ Snapshot から作成されるすべてのボリュームに適用される、新しいボリューム名のプレフィックスを入力します。
. （オプション）クローンを割り当てる別のアカウントを選択します。アカウントを選択しない場合、新しいボリュームは現在のボリュームアカウントに割り当てられます。
. クローン内のボリュームに適用する別のアクセス方法を選択します。方法を選択しない場合、現在のボリュームアクセスが使用されます。
+
** * 読み取り専用 * ：読み取り処理のみが許可されます。
** * 読み取り / 書き込み * ：すべての読み取り / 書き込み処理が許可されます。
** * Locked * ：管理者アクセスのみが許可されます。
** * レプリケーションターゲット * ：レプリケートされたボリュームペアのターゲットボリュームとして指定されます。


. [OK] をクリックします。
+

NOTE: クローニング処理が完了するまでの時間は、ボリュームサイズおよびクラスタの現在の負荷によって異なります。





== グループ Snapshot にボリュームをロールバックします

一連のアクティブボリュームをグループ Snapshot にロールバックできます。グループ Snapshot 内の関連付けられているすべてのボリュームが、グループ Snapshot が作成された時点の状態にリストアされます。この手順では、ボリュームサイズも元の Snapshot に記録されているサイズにリストアされます。ボリュームがパージされている場合は、そのボリュームのすべての Snapshot もパージ時に削除されています。削除されたボリューム Snapshot はリストアされません。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ グループスナップショット * （ Group Snapshots * ） ] サブタブをクリックします。
. ボリュームのロールバックに使用するグループ Snapshot のチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * グループ Snapshot へのボリュームのロールバック * を選択します。
. （オプション） Snapshot にロールバックする前にボリュームの現在の状態を保存するには、次の手順を実行します。
+
.. [ * スナップショットへのロールバック * ] ダイアログボックスで、 [ * ボリュームの現在の状態をグループスナップショットとして保存 * ] を選択します。
.. 新しい Snapshot の名前を入力します。


. [OK] をクリックします。




== グループ Snapshot を削除します

システムからグループ Snapshot を削除できます。グループ Snapshot を削除するときに、グループに関連付けられているすべての Snapshot について、削除するか個別の Snapshot として保持するかを選択できます。

グループ Snapshot に含まれているボリュームまたは Snapshot を削除すると、そのグループ Snapshot にロールバックできなくなります。ただし、各ボリュームを個別にロールバックすることは可能です。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. 削除するグループ Snapshot のチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 次のいずれかのオプションを選択します。
+
** * グループ Snapshot とメンバーを削除 * ：グループ Snapshot とすべてのメンバー Snapshot を削除します。
** * メンバーを保持 * ：グループ Snapshot を削除しますが、メンバー Snapshot はすべて保持されます。


. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

