---
sidebar: sidebar 
permalink: vcp_task_reports_alerts.html 
summary: アラートを監視する。このページでは、NetApp Element Plug-in for VMware vCenter Serverのレポートページを使用して、クラスタの稼働状況を示す情報、警告、またはエラーを確認できます。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= システムアラートを監視する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタの稼働状況を示す情報、警告、またはエラーであるアラートを監視できます。

アラートはクラスタの障害またはエラーであり、発生時に報告されます。ほとんどのエラーは自動的に解決しますが、一部のエラーでは手動での対応が必要です。アラートページの各アラートについて、アラートエラーコードが報告されます。エラーコードは、アラートが発生したシステムのコンポーネントおよびアラートが生成された理由を判断する場合に役立ちます。を参照してください link:vcp_reference_reports_alert_errors.html["システムアラートのリスト"] を参照してください。

問題を解決すると、システムが問題をポーリングし、解決済みであることを特定します。その後、アラートに関するすべての情報（解決日を含む）が解決済みビューに移動します。

.手順
. vCenter Plug-inで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


. [*Reporting*>*Alerts*] を選択します。
. 次のクラスタアラート情報を監視します。
+
** * ID * ：クラスタアラートの一意の ID 。
** * 重大度 *
+
*** * warning * ：近々対応が必要になる可能性があるが、マイナー問題。この重大度レベルでは、システムのアップグレードは引き続き可能です。
*** * error * ：原因のパフォーマンスが低下したり高可用性（ HA ）が失われたりする可能性のある障害です。通常、エラーがサービスに影響することはありません。
*** * critical * ：サービスに影響する深刻な障害です。システムは API 要求またはクライアント I/O 要求を処理できません。この状態で運用を続けると、データが失われる可能性があります。
*** * bestPractice * ：推奨されるシステム構成のベストプラクティスが使用されていません。


** * タイプ *
+
*** * node * ：ノード全体に影響する障害。
*** * drive * ：個々のドライブに影響する障害。
*** * cluster * ：クラスタ全体に影響する障害。
*** * service * ：クラスタ上のサービスに影響する障害。
*** * volume * ：クラスタ上のボリュームに影響する障害。


** * Node * ：この障害に関連するノードのノード ID 。エラーのタイプが node と drive の場合に表示され、それ以外の場合は - （ダッシュ）が表示されます。
** * Drive ID * ：この障害に関連するドライブのドライブ ID 。エラーのタイプが drive の場合に表示され、それ以外の場合は - （ダッシュ）が表示されます。
** * エラーコード * ：エラーの原因を示すコード。
** * 詳細 * ：障害の詳細な概要。
** * 時間 * ：この見出しは、アクティブフィルタビューでのみ表示されます。障害がログに記録された日時。
** * 解決日 * ：この見出しは、解決済みのフィルタビューにのみ表示されます。障害が解決された日時。


. 問題が解決されたことを確認するには、解決済みビューで を探します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

