---
sidebar: sidebar 
permalink: vcp_task_add_manage_nodes.html 
summary: プラグインを使用して、クラスタ構成内のノードを作成および管理できます。 
keywords: netapp, nodes, create, manage, delete, view vcp, vcenter, element 
---
= ノードを追加および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
プラグインを使用して、を追加できます https://docs.netapp.com/us-en/hci/docs/concept_hci_nodes.html#storage-nodes["ストレージノード"] クラスタを作成する場合やストレージの追加が必要な場合。Elementソフトウェアを実行しているストレージノードを追加することもできます。NetApp HCI コンピューティングノードは、vSphereのプラグイン以外の場所に追加する必要があります。

* <<クラスタにノードを追加します>>
* <<ノードの詳細を表示します>>
* <<ノードを再起動します>>
* <<ノードをシャットダウン>>
* <<クラスタからノードを削除します>>




== クラスタにノードを追加します

vCenter Plug-in を使用して、クラスタにストレージノードを追加できます。

.必要なもの
* 追加するノードのセットアップ、電源投入、設定を完了しておきます。
* ソフトウェアの互換性を確保するためには、クラスタ内の各ノードのソフトウェアのメジャーバージョン番号とマイナーバージョン番号が一致している必要があります。たとえば、 Element 9.0 とバージョン 9.1 は互換性がありません。



NOTE: 追加するノードの NetApp Element ソフトウェアのメジャーバージョンまたはマイナーバージョンがクラスタで実行されているバージョンと異なる場合、クラスタマスターで実行されている NetApp Element ソフトウェアのバージョンに非同期的に更新されます。更新されたノードは、自動的にクラスタに追加されます。この非同期プロセスの間 ' ノードの状態は pendingActive になります

.このタスクについて
ノードは、初回の電源投入時に初期設定を行う必要があります。ノードのセットアップと設定が完了すると、ノードはそのノードの設定時に識別されたクラスタに自身を登録し、プラグイン拡張ポイントの* Cluster > Nodes *ページにある保留中のノードのリストに表示されます。

既存のクラスタには、大小さまざまな容量のノードを追加できます。

手順 は、NetApp Element ソフトウェアを実行するFCノードまたはストレージノードを追加する場合と同じです。

.手順
. vSphere Web Clientで、* Cluster *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>クラスタ*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Cluster *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブをクリックします。
. ドロップダウンリストから「 * Pending * 」を選択して、ノードのリストを表示します。
. ノードを追加するには、次の手順を実行します。
+
.. 追加する各ノードのチェックボックスを選択します。
.. [ ノードの追加 ] をクリックします。


. 追加するノードの詳細を確認し、操作を確定します。
+
操作が完了すると、ノードがクラスタのアクティブノードのリストに表示されます。





== ノードの詳細を表示します

プラグイン拡張ポイントから、ClusterタブのNodesページにクラスタ内のノードのリストを表示できます。アクティブなノードのリストを表示するには、アクティブなビューを選択する必要があります。を選択すると、ビューを変更できます `Pending`、 `PendingActive`および `All` ドロップダウンフィルタを使用したオプション。

.手順
. vSphere Web Clientで、* Cluster *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>クラスタ*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Cluster *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
. [ アクティブ（ * Active ） ] ビューを選択します。
. ストレージクラスタ内のノードの詳細を表示します。
+
ノード ID 、各ノードの名前と状態、設定されている IOPS 、ノードタイプ、各ノードのアクティブドライブの数、各ノードのネットワーク情報などの情報を確認できます。





== ノードを再起動します

プラグイン拡張ポイントを使用して、クラスタ内の1つ以上のアクティブノードを再起動できます。

.必要なもの
同時に複数のノードを再起動する場合は、 I/O を停止し、すべての iSCSI セッションを切断しておきます。

.このタスクについて
クラスタを再起動するには、すべてのクラスタノードを選択して再起動します。


IMPORTANT: このメソッドは、ノードのすべてのネットワークサービスを再起動します。このため、ネットワーク接続が一時的に失われます。

.手順
. vSphere Web Clientで、* Cluster *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>クラスタ*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Cluster *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
+
.. アクティブ * ビューで、再起動する各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * Restart * 」を選択します。


. 操作を確定します。




== ノードをシャットダウン

Plug-in拡張ポイントを使用して、クラスタ内の1つ以上のアクティブノードをシャットダウンできます。クラスタをシャットダウンするには、すべてのクラスタノードを選択して同時にシャットダウンします。

.必要なもの
同時に複数のノードを再起動する場合は、 I/O を停止し、すべての iSCSI セッションを切断しておきます。

.手順
. vSphere Web Clientで、* Cluster *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>クラスタ*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Cluster *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
+
.. アクティブ * ビューで、シャットダウンする各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * Shutdown * 」を選択します。


. 操作を確定します。



NOTE: ノードが何らかの理由でシャットダウン状態になって 5 分半以上が経過すると、 NetApp Element ソフトウェアはノードが再びクラスタに参加することはないと判断します。Double Helix データ保護は、レプリケートされた個々のブロックを別のノードに書き込んでデータをレプリケートするタスクを開始します。ノードがシャットダウンしていた時間によっては、ノードがオンラインに戻ったあとにドライブを再度クラスタに追加する必要があります。



== クラスタからノードを削除します

ノードのストレージが不要になったときや、ノードのメンテナンスが必要なときは、サービスを中断することなくクラスタからノードを削除できます。

.必要なもの
ノード内のすべてのドライブをクラスタから削除しておきます。RemoveDrives プロセスが完了してすべてのデータがノードから移行されるまで、ノードを削除することはできません。

.このタスクについて
NetApp Element クラスタでのFC接続には、少なくとも2つのFCノードが必要です。FCノードが1つしか接続されていない場合は、クラスタに別のFCノードを追加するまでイベントログにアラートが記録されます。これは、すべてのFCネットワークトラフィックが1つのFCノードでのみ処理を続けている場合でも同様です。

.手順
. vSphere Web Clientで、* Cluster *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>クラスタ*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Cluster *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ ノード * （ Nodes * ） ] サブタブを選択します。
. 1 つ以上のノードを削除するには、次の手順を実行します。
+
.. アクティブ * ビューで、削除する各ノードのチェックボックスを選択します。
.. [* アクション * ] をクリックします。
.. 「 * 削除」を選択します。


. 操作を確定します。
+
クラスタから削除したノードがすべて Pending 状態のノードのリストに表示されます。





== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

