---
sidebar: sidebar 
permalink: vcp_task_create_manage_user_accounts.html 
summary: プラグインを使用して、ユーザアカウントを作成および管理できます。 
keywords: netapp, storage, accounts, vcp, vcenter, element 
---
= ユーザアカウントを作成および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:vcp_concept_accounts.html["ユーザアカウント"] NetApp Element ソフトウェアベースのネットワーク上のストレージリソースへのアクセスを制御するために使用されます。

.オプション（ Options ）
* <<アカウントを作成します>>
* <<アカウントを編集します>>
* <<アカウントを削除します>>




== アカウントを作成します

ストレージボリュームへのアクセスを許可する一意のユーザアカウントを作成できます。

.必要なもの
* クラスタが少なくとも 1 つ追加されて実行されている必要があります。


.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アカウント * （ Accounts * ） ] サブタブを選択します。
. 「 * アカウントの作成 * 」を選択します。
. ユーザ名を入力します。
+

TIP: わかりやすい名前のベストプラクティスを使用してください。これは、環境で複数のクラスタや vCenter Server を使用している場合に特に重要です。

. [* CHAP 設定 * （ CHAP Settings * ） ] セクションで、次の操作
+
.. ノードセッションの CHAP 認証用イニシエータシークレットを入力します。
.. ノードセッションの CHAP 認証用ターゲットシークレットを入力します。
+

NOTE: イニシエータとターゲットには違うシークレットを指定する必要これらのフィールドを空白にすると、システムによって認証クレデンシャルが生成されます。



. [OK] をクリックしてアカウントを作成します。




== アカウントを編集します

ユーザアカウントを編集して、ステータスまたは CHAP シークレットを変更できます。CHAP 設定を変更すると、原因がホストと関連付けられているボリュームの間の接続を切断する可能性があります。

.このタスクについて
管理ノードに永続ボリュームを使用している場合は、永続ボリュームに関連付けられているアカウントの名前を変更しないでください。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アカウント * （ Accounts * ） ] サブタブを選択します。
. 編集するアカウントのチェックボックスを選択します。
. [ * アクション * ] を選択します。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. 必要に応じて次の項目を変更します。
+
.. アカウントのアクセスステータスを編集します。
+

IMPORTANT: アクセスを「 * Locked 」に変更すると、アカウントへのすべての iSCSI 接続が切断され、アカウントにアクセスできなくなります。アカウントに関連付けられているボリュームは維持されますが、 iSCSI で検出できなくなります。

.. ノードセッションの認証に使用するイニシエータシークレットとターゲットシークレットのクレデンシャルを編集します。
+

NOTE: クレデンシャルを変更しない場合、同じクレデンシャルが使用されます。クレデンシャルのフィールドを空白にすると、システムによって新しいパスワードが生成されます。



. [OK] をクリックします。




== アカウントを削除します

プラグイン拡張ポイントを使用して、ユーザアカウントを削除できます。

.必要なもの
アカウントに関連付けられているボリュームを削除およびパージするか、別のアカウントに割り当て直します。


IMPORTANT: 管理ノードに永続ボリュームを使用している場合、永続ボリュームに関連付けられているアカウントは削除しないでください。

.手順
. vSphere Web Clientで、* Management *タブを開きます。
+
** Element vCenterプラグイン5.0以降では、* NetApp Element リモートプラグイン>管理>管理*を選択します。
** Element vCenterプラグイン4.10以前の場合は、* NetApp Element Management > Management *を選択します。


+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ アカウント * （ Accounts * ） ] サブタブを選択します。
. 削除するアカウントのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

