---
sidebar: sidebar 
permalink: vcp_task_protect_snapshots_schedules.html 
summary: プラグインを使用して Snapshot スケジュールを作成します。 
keywords: netapp, hci, vcp, vcenter, element, protect, snapshots, schedule 
---
= Snapshot スケジュールを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
指定した間隔で Snapshot を自動的に作成するように、ボリュームの Snapshot のスケジュールを設定できます。1 つのボリューム Snapshot またはグループ Snapshot を自動的に実行するようにスケジュールを設定できます。

ボリュームがレプリケートされている場合、 Snapshot スケジュールの作成時に、作成された Snapshot をリモートの NetApp Element ストレージシステムに格納するように設定できます。


NOTE: スケジュールは UTC+0 時間を使用して作成されます。タイムゾーンに基づいて、 Snapshot が実行される実際の時刻の調整が必要になる場合があります。

*  a snapshot schedule
*  snapshot schedule details
*  a snapshot schedule
*  a snapshot schedule
*  a snapshot schedule




== Snapshot スケジュールを作成します

ボリュームの Snapshot のスケジュールを設定し、指定した間隔で Snapshot を自動的に作成できます。

Snapshot スケジュールには、曜日または日にちに基づく間隔を設定できます。次の Snapshot を作成するまでの日数、時間、および分を指定することもできます。

Snapshot のスケジュールを 5 分以外の間隔で設定した場合、 Snapshot は 5 分単位に繰り上げた時間で実行されます。たとえば、 12 ： 42 ： 00 UTC に実行するように Snapshot のスケジュールを設定した場合、 12 ： 45 ： 00 UTC に実行されます。Snapshot のスケジュールを 5 分未満の間隔で実行するように設定することはできません。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ * Schedules * （スケジュール * ） ] サブタブを選択します。
. ［ * スケジュールの作成 * ］ を選択します。
. 「 * ボリューム ID CSV * 」フィールドに、 Snapshot スケジュールの処理対象に含めるボリューム ID をカンマで区切って入力します。
. スケジュール名を入力します。
. スケジュールタイプを選択し、詳細を設定します。
. （任意）無期限にスケジュールを繰り返すには、 [*Recurring Schedule*] をオンにします。
. （オプション） New Snapshot Name フィールドに、新しい Snapshot の名前を入力します。
+

NOTE: 名前を入力しない場合、デフォルトでは、 Snapshot の作成日時が名前として使用されます。

. （オプション） * ペアリング時に Snapshot をレプリケーションに含める * をオンにして、親ボリュームがペアリングされたときに Snapshot がレプリケートされることを確認します。
. Snapshot の保持期間として次のいずれかを選択します。
+
** * 永続的に保持 * ： Snapshot をシステム上に無期限に保持します。
** * 保存期間の設定 * ：システムがスナップショットを保持する期間（日数、時間、または分）を指定します。
+

NOTE: 保持期間には、現在の時刻からの期間を選択します。（保持期間は Snapshot の作成時間からは計算されません）。



. 「 * OK 」を選択します。




== Snapshot スケジュールの詳細を表示します

Snapshot スケジュールの詳細を検証することができます。

.手順
. vCenter Plug-in で、 * NetApp Element 管理 * > * 保護 * を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、表示するクラスタがナビゲーションバーで選択されていることを確認してください。

. [* Schedules * （スケジュール * ） ] ページを選択します
. スケジュールの詳細を確認




== Snapshot スケジュールを編集します

既存の Snapshot スケジュールを変更できます。変更後、次回のスケジュール実行時に更新された属性が使用されます。元のスケジュールで作成された Snapshot はストレージシステムに保持されます。

.手順
. ［ * NetApp Element 管理 ］ > ［ 保護 * ］ を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ * Schedules * （スケジュール * ） ] サブタブをクリックします。
. 編集する Snapshot スケジュールのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. 「 * Volume IDs CSV * 」フィールドで、 Snapshot 処理に現在含まれている単一のボリューム ID またはカンマで区切ったボリューム ID のリストを変更します。
. （オプション）アクティブなスケジュールを一時停止したり、一時停止したスケジュールを再開したりするには、 * スケジュールを手動で一時停止 * チェックボックスをオンにします。
. （オプション） [ 新しいスケジュール名 * ] フィールドにスケジュールの別の名前を入力します。
. （オプション）現在のスケジュールタイプを次のいずれかに変更します。
+
.. * 曜日 * ： Snapshot を作成する曜日と時刻をさらに 1 日選択します。
.. * Days of Month * ： Snapshot を作成する日にちと時刻を選択します。
.. * Time Interval * ： Snapshot を作成する日数、時間、分数に基づいて実行するスケジュールの間隔を選択します。


. （オプション） * RecurrentSchedule * を選択して、 Snapshot スケジュールを無期限に繰り返します。
. （オプション）スケジュールで定義された Snapshot の名前を「 * New Snapshot Name * 」フィールドに入力または変更します。
+

NOTE: このフィールドを空白のままにすると、 Snapshot の作成日時が名前として使用されます。

. （オプション） * ペアリング時にスナップショットを複製に含める * チェックボックスをオンにして、親ボリュームがペアリングされているときにスナップショットが複製にキャプチャされるようにします。
. （オプション） Snapshot の保持期間として次のいずれかを選択します。
+
** * 永続的に保持 * ： Snapshot をシステム上に無期限に保持します。
** * 保存期間の設定 * ：システムがスナップショットを保持する期間（日数、時間、または分）を指定します。
+

NOTE: 保持期間には、（ Snapshot の作成時間からではなく）現在の時刻からの期間を指定します。



. [OK] をクリックします。




== Snapshot スケジュールをコピーします

Snapshot スケジュールのコピーを作成して、新しいボリュームに割り当てたり他の目的に使用したりできます。

.手順
. ［ * NetApp Element 管理 ］ > ［ 保護 * ］ を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ * Schedules * （スケジュール * ） ] サブタブをクリックします。
. コピーする Snapshot スケジュールのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * Copy * をクリックします。Copy Schedule （スケジュールのコピー）ダイアログボックスが表示され、スケジュールの現在の属性が設定されます。
. （オプション）コピーしたスケジュールの名前を入力し、設定を更新します。
. [OK] をクリックします。




== Snapshot スケジュールを削除します

Snapshot スケジュールを削除できます。スケジュールを削除すると、以降のスケジュールされた Snapshot は実行されません。過去にスケジュールで作成された Snapshot はストレージシステム上に保持されます。

.手順
. ［ * NetApp Element 管理 ］ > ［ 保護 * ］ を選択します。
+

NOTE: 複数のクラスタが追加されている場合は、このタスクに使用するクラスタがナビゲーションバーで選択されていることを確認してください。

. [ * Schedules * （スケジュール * ） ] サブタブをクリックします。
. 削除する Snapshot スケジュールのチェックボックスを選択します。
. [* アクション * ] をクリックします。
. 表示されたメニューで、 * 削除 * をクリックします。
. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

